Repository ovh/cds, pull requests merged in 2018-05, with the labels that each got.

#2615 feat(api): add pprof http label and enable GET method to run with pprof
  Gopkg.lock
  engine/api/api_routes.go
  engine/api/router.go
  vendor/github.com/rakyll/goutil/LICENSE
  vendor/github.com/rakyll/goutil/opencensus/LICENSE
  vendor/github.com/rakyll/goutil/pprofutil/grpc.go
  vendor/github.com/rakyll/goutil/pprofutil/http.go
Labels: review

#2619 fix(hook): after a cron update the task which is already planned is not refresh close #2613
  engine/hooks/hooks_handlers.go
Labels: bug, review

#2618 fix(sql): move constraint for subnum
  engine/sql/090_unique_subnum.sql
Labels: review

#2622 fix(api): fix multiple same subnum, do not reprocess all workflow for nothing
  engine/api/workflow/dao_node_run.go
  engine/api/workflow/execute_node_run.go
  engine/api/workflow/process.go
Labels: review

#2625 fix(api): fix edit default payload with application without repo linked
  engine/api/workflow.go
Labels: bug

#2623 Add DisableTempURL for the ability to disable temporary URL use in Swift
  engine/api/api.go
  engine/api/objectstore/objectstore.go
Labels: next

#2620 feat (engine): openstack auth v3
  engine/api/api.go
  engine/api/objectstore/objectstore.go
  engine/api/objectstore/swift.go
  engine/hatchery/openstack/init.go
  engine/hatchery/openstack/openstack.go
  engine/hatchery/openstack/types.go
Labels: review

#2663 fix(api): fix update node run for a worker export
  engine/api/workflow/dao_node_run.go
  engine/api/workflow_queue.go
Labels: bug

#2665 fix(plugin): fix ssh-cmd config
  contrib/plugins/plugin-ssh-cmd/ssh.go
Labels: bug

#2666 fix(api): import pipeline with forceUpdate guarantee new order or stages
  engine/api/pipeline/pipeline_importer.go
  engine/api/pipeline/pipeline_importer_test.go
  engine/api/pipeline/pipeline_stage.go
Labels: bug

#2675 fix(sql): drop index before create a new one on workflow
  engine/sql/094_workflow_name_unique.sql
Labels: bug

#2671 refactor(api): optimise slice and map allocation
  engine/api/workflow/execute_node_job_run.go
  engine/api/workflow/process_parameters.go
  sdk/exportentities/action.go
  sdk/exportentities/pipeline.go
  sdk/exportentities/workflow.go
  sdk/parameter.go
  sdk/plugin/common.go
  sdk/plugin/types.go
  sdk/stage.go
  sdk/util.go
  sdk/vcs/git/git.go
  sdk/workflow.go
Labels: refactor

#2684 feat(ui): add broadcasts display in UI
  engine/api/api_routes.go
  engine/api/broadcast.go
  engine/api/broadcast/broadcast.go
  engine/api/broadcast/gorp_model.go
  engine/api/broadcast_test.go
  engine/api/user.go
  engine/sql/096_broadcast_user.sql
  sdk/broadcast.go
  ui/.angular-cli.json
  ui/src/app/app.routing.ts
  ui/src/app/model/broadcast.model.ts
  ui/src/app/service/broadcast/broadcast.service.ts
  ui/src/app/service/language/language.store.ts
  ui/src/app/shared/favorite-cards/favorite-cards.component.html
  ui/src/app/shared/favorite-cards/favorite-cards.component.scss
  ui/src/app/shared/favorite-cards/favorite-cards.component.ts
  ui/src/app/views/admin/broadcast/add/broadcast.add.component.ts
  ui/src/app/views/admin/broadcast/edit/broadcast.edit.component.ts
  ui/src/app/views/broadcast/broadcast.module.ts
  ui/src/app/views/broadcast/broadcast.routing.ts
  ui/src/app/views/broadcast/details/broadcast.details.component.html
  ui/src/app/views/broadcast/details/broadcast.details.component.scss
  ui/src/app/views/broadcast/details/broadcast.details.component.ts
  ui/src/app/views/broadcast/list/broadcast.list.component.html
  ui/src/app/views/broadcast/list/broadcast.list.component.scss
  ui/src/app/views/broadcast/list/broadcast.list.component.ts
  ui/src/app/views/home/home.component.ts
  ui/src/app/views/home/home.html
  ui/src/app/views/home/home.scss
  ui/src/app/views/navbar/navbar.component.ts
  ui/src/app/views/navbar/navbar.html
  ui/src/app/views/navbar/navbar.scss
  ui/src/assets/i18n/en.json
  ui/src/assets/i18n/fr.json
Labels: enhancement

#2693 feat(ui): add ui.run url in build parameters
  engine/api/api.go
  engine/api/workflow/init.go
  engine/api/workflow/process.go
Labels: enhancement

#2695 fix(ui): fix line break for broadcast
  ui/src/app/views/broadcast/details/broadcast.details.component.html
  ui/src/app/views/broadcast/list/broadcast.list.component.html
Labels: hotfix

#2699 fix(ui): add withPermission for export pipeline
  ui/src/app/service/pipeline/pipeline.service.ts
Labels: hotfix

#2713 fix(ui): fix error on ui action page
  ui/src/app/shared/action/action.html
Labels: bug

#2714 docs(workflow): fix documentation on worker model docker
  docs/content/workflows/pipelines/requirements/worker-model/docker/docker-customized.md
Labels: doc

#2747 feat(ui): add search for binary capabilities inside worker model
  cli/cdsctl/worker_model.go
  engine/api/worker/model.go
  engine/api/worker/model_test.go
  engine/api/worker_model.go
  sdk/cdsclient/client_worker_model.go
  sdk/cdsclient/interface.go
  tests/clictl_worker_model.yml
  ui/src/app/service/worker-model/worker-model.service.ts
  ui/src/app/views/admin/broadcast/list/broadcast.list.component.ts
  ui/src/app/views/settings/worker-model/list/worker-model.list.component.ts
  ui/src/app/views/settings/worker-model/list/worker-model.list.html
  ui/src/app/views/settings/worker-model/list/worker-model.list.scss
  ui/src/assets/i18n/en.json
  ui/src/assets/i18n/fr.json
Labels: enhancement
