Repository ovh/cds, pull requests merged in 2018-06, with the labels that each got.

#2792 test(api): add benchmark for workflows
  engine/api/test/test.go
  engine/api/workflow_test.go
  sdk/log/log.go
Labels: tests

#2793 fix(api): add history length on workflow as code
  engine/api/workflow/workflow_exporter.go
  engine/api/workflow_export_test.go
  sdk/exportentities/workflow.go
  sdk/exportentities/workflow_test.go
Labels: bug

#2811 feat(ui): update queue view in settings
  ui/src/app/views/settings/queue/queue.component.html
  ui/src/app/views/settings/queue/queue.component.ts
Labels: bug

#2815 fix(api): keep at least one success run in purge
  engine/api/workflow/dao_node_run.go
  engine/api/workflow/dao_run.go
  engine/api/workflow/dao_run_test.go
Labels: bug

#2824 fix(api): avoid delete the last rwx group on app/env/wf/pip #2809
  engine/api/application_group.go
  engine/api/application_group_test.go
  engine/api/group/application_group.go
  engine/api/project_group.go
Labels: bug

#2838 feat(ui): add better notification popup
  ui/src/app/views/navbar/navbar.component.ts
  ui/src/app/views/navbar/navbar.html
  ui/src/app/views/navbar/navbar.scss
  ui/src/assets/i18n/en.json
  ui/src/assets/i18n/fr.json
Labels: enhancement

#2846 fix(ui): fix style of bookmarks
  ui/src/app/views/navbar/navbar.scss
Labels: bug

#2844 fix(ui): fix width of workflow graph
  ui/src/app/views/workflow/graph/workflow.graph.component.ts
Labels: bug

#2851 fix(ui): add link in broadcast list
  ui/src/app/views/navbar/navbar.html
  ui/src/app/views/navbar/navbar.scss
Labels: bug

#2852 fix(sdk): fix add multiple tag value
  sdk/workflow_run.go
  sdk/workflow_run_test.go
Labels: bug

#2848 fix(api): fix commit list
  engine/api/workflow/dao_node_run.go
Labels: bug

#2857 fix(sdk): fix interpolate with dash into helper
  sdk/interpolate/interpolate.go
  sdk/interpolate/interpolate_test.go
Labels: bug

#2858 feat(ui): add different title for each view
  ui/package.json
  ui/src/app/app.component.ts
  ui/src/app/app.routing.ts
  ui/src/app/views/account/account.routing.ts
  ui/src/app/views/admin/admin.routing.ts
  ui/src/app/views/application/application.routing.ts
  ui/src/app/views/pipeline/pipeline.routing.ts
  ui/src/app/views/project/project.routing.ts
  ui/src/app/views/settings/settings.routing.ts
  ui/src/app/views/workflow/workflow.routing.ts
  ui/tslint.json
Labels: enhancement

#2862 fix(api): fix worker cache for symlink directory
  engine/api/cache.go
  engine/worker/cmd_cache.go
  sdk/cache.go
Labels: bug

#2866 fix(ui): login page redirect in all cases
  ui/src/app/service/logout.interceptor.service.ts
Labels: bug

#2864 feat(ui): add better list view as project list
  engine/api/project/dao_dependencies.go
  engine/api/workflow/dao.go
  sdk/common.go
  sdk/project.go
  ui/src/app/model/project.model.ts
  ui/src/app/views/project/show/application/application.list.html
  ui/src/app/views/project/show/pipeline/pipeline.list.html
  ui/src/app/views/project/show/workflow/workflow.list.component.ts
  ui/src/app/views/project/show/workflow/workflow.list.html
  ui/src/app/views/project/show/workflow/workflow.list.scss
  ui/src/app/views/workflow/add/workflow.add.component.ts
  ui/src/assets/i18n/en.json
  ui/src/assets/i18n/fr.json
Labels: enhancement

#2873 fix(ui): fix tab link for node run
  ui/src/app/views/workflow/run/node/workflow.run.node.component.ts
Labels: bug

#2868 feat(vcs): add proxy configuration for webhook (public url) close #2865
  docs/content/hosting/repositories-manager/bitbucket.md
  docs/content/hosting/repositories-manager/github.md
  docs/content/hosting/repositories-manager/gitlab.md
  engine/api/workflow/hook.go
  engine/vcs/bitbucket/bitbucket.go
  engine/vcs/bitbucket/bitbucket_test.go
  engine/vcs/bitbucket/client_hook.go
  engine/vcs/github/client_hook.go
  engine/vcs/github/github.go
  engine/vcs/github/github_test.go
  engine/vcs/github/oauth_consumer.go
  engine/vcs/gitlab/client_hook.go
  engine/vcs/gitlab/gitlab.go
  engine/vcs/gitlab/gitlab_test.go
  engine/vcs/types.go
  engine/vcs/vcs.go
Labels: enhancement

#2878 fix(ui): fix usage links
  ui/src/app/shared/usage/applications/usage.applications.html
  ui/src/app/shared/usage/environments/usage.environments.html
  ui/src/app/shared/usage/pipelines/usage.pipelines.html
  ui/src/app/shared/usage/workflows/usage.workflows.html
Labels: hotfix

#2874 fix(ui): change title view of login page for keepass autocompletion
  ui/src/app/views/account/account.routing.ts
Labels: bug

#2879 fix(ui): fix pipeline params display and slow UI
  engine/api/workflow/dao_run.go
  ui/src/app/shared/parameter/value/parameter.value.component.ts
  ui/src/app/shared/workflow/node/context/workflow.node.context.component.ts
  ui/src/app/shared/workflow/node/run/node.run.param.component.ts
  ui/src/app/shared/workflow/node/workflow.node.component.ts
Labels: bug

#2888 fix(ui): do not redirect to the login page after login
  ui/src/app/service/auth/authenRouteActivate.ts
  ui/src/app/service/logout.interceptor.service.ts
Labels: bug

#2890 fix(api): push artifact on object store with ref instead of tag
  engine/api/api.go
  engine/api/api_routes.go
  engine/api/cache.go
  engine/api/migrate/hatchery_cmd.go
  engine/api/migrate/workflow_node_run_artifacts.go
  engine/api/workflow/dao_artifact.go
  engine/api/workflow_queue_artifact.go
  engine/api/workflow_queue_test.go
  engine/api/workflow_run.go
  engine/sql/104_artifact_ref.sql
  engine/worker/builtin_artifact_upload.go
  engine/worker/cmd_cache.go
  engine/worker/cmd_download.go
  engine/worker/cmd_server.go
  sdk/artifact.go
  sdk/cdsclient/client_queue.go
  sdk/cdsclient/client_workflow.go
  sdk/cdsclient/interface.go
  sdk/workflow_run.go
Labels: bug

#2892 feat(api): clean old archived broadcasts
  engine/api/api.go
  engine/api/broadcast/broadcast.go
  engine/api/broadcast/init.go
  engine/api/workflow/init.go
Labels: enhancement

#2908 fix(api): fix resync vcs to postexecute and fix migrate artifact
  engine/api/api_routes.go
  engine/api/migrate/workflow_node_run_artifacts.go
Labels: bug

#2912 fix (api): update deployment strategy
  sdk/platform.go
Labels: hotfix

#2942 fix(ui): don't display no new commit when no repo is linked on run modal #2929
  ui/src/app/shared/workflow/node/run/node.run.param.component.ts
  ui/src/app/shared/workflow/node/run/node.run.param.html
  ui/src/app/views/home/timeline/home.timeline.html
  ui/src/assets/i18n/en.json
  ui/src/assets/i18n/fr.json
Labels: bug

#2941 feat(api,ui,hatchery): add logs on service
  engine/api/action/requirement.go
  engine/api/api_routes.go
  engine/api/group/pipeline_group.go
  engine/api/pipeline/build_log.go
  engine/api/pipeline/pipeline.go
  engine/api/workflow/execute_node_job_run.go
  engine/api/workflow/execute_node_job_run_log_service.go
  engine/api/workflow_queue.go
  engine/api/workflow_run.go
  engine/hatchery/swarm/swarm.go
  engine/hatchery/swarm/swarm_util_logs.go
  engine/sql/108_service_log.sql
  sdk/cdsclient/client_queue.go
  sdk/cdsclient/interface.go
  sdk/log.pb.go
  sdk/log.proto
  sdk/requirement.go
  sdk/requirement_easyjson.go
  ui/src/app/model/pipeline.model.ts
  ui/src/app/service/workflow/run/workflow.run.service.ts
  ui/src/app/views/home/favorite/home.favorite.html
  ui/src/app/views/home/favorite/home.favorite.scss
  ui/src/app/views/home/home.scss
  ui/src/app/views/workflow/run/node/pipeline/node.pipeline.component.ts
  ui/src/app/views/workflow/run/node/pipeline/pipeline.html
  ui/src/app/views/workflow/run/node/pipeline/service/service.log.component.ts
  ui/src/app/views/workflow/run/node/pipeline/service/service.log.html
  ui/src/app/views/workflow/run/node/pipeline/service/service.log.scss
  ui/src/app/views/workflow/run/node/pipeline/spawninfo/spawninfo.component.ts
  ui/src/app/views/workflow/run/node/pipeline/spawninfo/spawninfo.html
  ui/src/app/views/workflow/run/node/pipeline/spawninfo/spawninfo.scss
  ui/src/app/views/workflow/workflow.module.ts
Labels: enhancement

#2949 feat(api): add config for the default os and arch to launch
  engine/api/api.go
  engine/api/workflow/dao_node_run_job.go
  engine/api/workflow/init.go
  sdk/hatchery/hatchery.go
Labels: enhancement

#2951 fix(api): fix add service logs
  engine/api/workflow/execute_node_job_run_log_service.go
  engine/hatchery/swarm/swarm.go
Labels: bug

#2954 feat(ui): add webworker for service logs
  ui/src/app/model/pipeline.model.ts
  ui/src/app/views/workflow/run/node/pipeline/node.pipeline.component.ts
  ui/src/app/views/workflow/run/node/pipeline/pipeline.html
  ui/src/app/views/workflow/run/node/pipeline/service/service.log.component.ts
  ui/src/app/views/workflow/run/node/pipeline/service/service.log.html
  ui/src/assets/worker/web/workflow-service-log.js
Labels: enhancement

#2956 fix(ui): delete branch and default branch from the ui and add warning
  cli/cdsctl/workflow_as_code.go
  engine/api/application/application_parser.go
  engine/api/ascode.go
  engine/api/workflow/process_parameters.go
  sdk/application.go
  sdk/exportentities/application.go
  ui/src/app/model/vcs.model.ts
  ui/src/app/shared/vcs/vcs.strategy.html
  ui/src/app/views/application/show/admin/repository/application.repo.component.ts
  ui/src/app/views/application/show/admin/repository/application.repo.html
  ui/src/app/views/application/show/admin/repository/application.repo.scss
  ui/src/app/views/workflow/add/workflow.add.component.ts
  ui/src/assets/i18n/en.json
  ui/src/assets/i18n/fr.json
Labels: enhancement

#2957 feat(ui): add edit description on workflow #2915
  sdk/exportentities/workflow.go
  sdk/exportentities/workflow_test.go
  ui/src/app/views/workflow/show/admin/workflow.admin.component.html
  ui/src/app/views/workflow/show/admin/workflow.admin.scss
Labels: enhancement
