Repository ovh/cds, pull requests merged in 2018-04, with the labels that each got.

#2467 doc: cdsctl action import
  contrib/actions/cds-docker-package.yml
  contrib/actions/cds-go-build.yml
  contrib/actions/cds-nexus-upload.yml
  contrib/actions/cds-perl-test.yml
  contrib/actions/cds-publish-ovh-metrics.yml
  contrib/actions/cds-python-pylint.yml
  docs/build.sh
  docs/content/workflows/pipelines/actions/user/_index.md
Labels: review

#2524 fix(ui): fix scroll on import pipeline
  ui/src/app/views/pipeline/add/pipeline.add.html
  ui/src/app/views/pipeline/add/pipeline.add.scss
Labels: bug

#2528 fix(api): workflow import default history length
  engine/.debpacker.yml
  engine/api/workflow/workflow_importer.go
Labels: hotfix

#2552 fix(api): edit payload keep the changes
  engine/api/workflow.go
  ui/src/app/views/workflow/show/workflow.html
Labels: bug, review

#2554 feat (cds2es): add fields
  contrib/uservices/cds2es/process.go
Labels: review

#2553 fix(api): interpolate should not be replaced git.branch as git__branch
  sdk/interpolate/interpolate.go
  sdk/interpolate/interpolate_test.go
Labels: review

#2555 fix(api): do not add default tags if there already some tags setted #2532
  engine/api/migrate/default_payload.go
  engine/api/workflow.go
  engine/api/workflow/dao.go
  engine/api/workflow/hook.go
  engine/api/workflow/workflow_run_event.go
  engine/api/workflow_hook.go
  engine/api/workflow_test.go
  engine/api/workflow_trigger.go
  sdk/workflow.go
Labels: review

#2556 fix(api): fix parse workflow in import workflow for hook config
  engine/Makefile
  sdk/exportentities/workflow.go
  sdk/exportentities/workflow_test.go
  sdk/hook.go
  sdk/workflow_test.go
Labels: bug, review

#2558 doc: typo
  docs/content/gettingstarted/_index.md
Labels: review

#2560 fix(sdk): fix unit tests about pipeline export import
  sdk/exportentities/pipeline_test.go
Labels: review

#2561 fix (vcs): take remaining header only on http OK
  engine/vcs/github/http.go
Labels: review

#2563 fix(api): avoid try store more than maxlength tags
  engine/api/workflow/dao_run.go
Labels: review

#2565 fix (vcs): no warn log if Branch not found
  engine/vcs/bitbucket/types.go
  engine/vcs/github/client_event.go
Labels: review

#2559 fix(api): if repository manager return an error for default payload it should not block the workflow update
  engine/api/workflow.go
Labels: bug, review

#2567 fix(ui): fix sidebar for node run
  ui/src/app/model/workflow.run.model.ts
  ui/src/app/shared/workflow/node/run/node.run.param.component.ts
  ui/src/app/views/workflow/add/workflow.add.html
  ui/src/app/views/workflow/run/workflow.run.component.ts
  ui/src/assets/worker/web/workflow2.js
Labels: review

#2566 doc: style
  docs/content/gettingstarted/_index.md
  docs/content/gettingstarted/concepts/why_cds.md
  docs/content/gettingstarted/import_workflow_with_webui.md
  docs/content/gettingstarted/init_workflow_with_cdsctl.md
  docs/content/gettingstarted/step_by_step_build_deploy.md
  docs/layouts/shortcodes/expand.html
Labels: review

#2569 refactor (service): common heartbeat
  engine/api/api.go
  engine/api/services/const.go
  engine/hatchery/kubernetes/kubernetes.go
  engine/hatchery/kubernetes/types.go
  engine/hatchery/local/local.go
  engine/hatchery/local/types.go
  engine/hatchery/marathon/marathon.go
  engine/hatchery/marathon/types.go
  engine/hatchery/openstack/openstack.go
  engine/hatchery/openstack/types.go
  engine/hatchery/swarm/swarm_conf.go
  engine/hatchery/swarm/types.go
  engine/hatchery/vsphere/types.go
  engine/hatchery/vsphere/vsphere.go
  engine/hooks/heartbeat.go
  engine/hooks/hooks.go
  engine/hooks/hooks_auth.go
  engine/hooks/hooks_handlers.go
  engine/hooks/hooks_router.go
  engine/hooks/kafka.go
  engine/hooks/tasks.go
  engine/hooks/types.go
  engine/main.go
  engine/repositories/heartbeat.go
  engine/repositories/repositories.go
  engine/repositories/repositories_handlers.go
  engine/repositories/repositories_test.go
  engine/repositories/types.go
  engine/service/heartbeat.go
  engine/service/service.go
  engine/types.go
  engine/vcs/github/client_event.go
  engine/vcs/github/http.go
  engine/vcs/github/status.go
  engine/vcs/types.go
  engine/vcs/vcs.go
  engine/vcs/vcs_auth.go
  engine/vcs/vcs_handlers.go
  engine/vcs/vcs_router.go
  engine/vcs/vcs_test.go
  sdk/hatchery/register.go
Labels: review

#2572 feat (engine): status on all services, api too
  cli/cdsctl/admin_services.go
  cli/cdsctl/monitoring.go
  engine/api/admin.go
  engine/api/api.go
  engine/api/api_routes.go
  engine/api/event/event.go
  engine/api/services.go
  engine/api/services/dao.go
  engine/api/status.go
  engine/hatchery/kubernetes/kubernetes.go
  engine/hatchery/kubernetes/types.go
  engine/hatchery/local/local.go
  engine/hatchery/local/types.go
  engine/hatchery/marathon/marathon.go
  engine/hatchery/marathon/types.go
  engine/hatchery/openstack/init.go
  engine/hatchery/openstack/openstack.go
  engine/hatchery/openstack/types.go
  engine/hatchery/serve.go
  engine/hatchery/swarm/swarm.go
  engine/hatchery/swarm/swarm_conf.go
  engine/hatchery/swarm/types.go
  engine/hatchery/vsphere/init.go
  engine/hatchery/vsphere/types.go
  engine/hatchery/vsphere/vsphere.go
  engine/hooks/hooks_handlers.go
  engine/hooks/types.go
  engine/main.go
  engine/repositories/repositories_handlers.go
  engine/repositories/types.go
  engine/service/heartbeat.go
  engine/service/service.go
  engine/sql/089_service_status.sql
  engine/vcs/types.go
  engine/vcs/vcs_handlers.go
  engine/vcs/vcs_router.go
  sdk/cdsclient/client_admin.go
  sdk/cdsclient/interface.go
  sdk/hatchery/hatchery.go
  sdk/hatchery/register.go
  sdk/services.go
  sdk/status.go
  tests/clictl_admin_services.yml
Labels: review

#2577 feat (engine): do not erase hash of hatchery
  engine/api/services/dao.go
  sdk/cdsclient/client_services.go
Labels: review

#2578 fix (hatcher): router on hatcheryCommon
  engine/hatchery/kubernetes/types.go
  engine/hatchery/marathon/types.go
  engine/hatchery/openstack/types.go
  engine/hatchery/swarm/types.go
  engine/hatchery/vsphere/types.go
Labels: review

#2581 fix (hatchery): call status on not fully initialized service
  engine/hatchery/kubernetes/kubernetes.go
  engine/hatchery/local/local.go
  engine/hatchery/marathon/marathon.go
  engine/hatchery/openstack/openstack.go
  engine/hatchery/serve.go
  engine/hatchery/swarm/swarm_conf.go
  engine/hatchery/vsphere/vsphere.go
  sdk/hatchery/hatchery.go
  sdk/hatchery/register.go
Labels: review

#2582 feat (engine,cdsctl): improve global status compute
  cli/cdsctl/monitoring.go
  engine/api/status.go
Labels: review

#2583 fix (hatchery): register user's hatchery as service
  engine/api/services.go
Labels: review

#2584 fix (services/vcs): default value of status
  engine/vcs/github/status.go
Labels: review

#2585 fix (service/hook): decode payload with godump
  engine/api/api.go
  engine/api/migrate/default_payload.go
  engine/api/migrate/default_tags.go
  engine/api/workflow/hook.go
Labels: review

#2571 doc: example of curl for webhook
  docs/content/workflows/design/hooks/webhook.md
Labels: doc, ready, review

#2588 fix (engine): load project - avoid lock on job not found
  cli/cdsctl/admin_hooks.go
  engine/api/cache/cache.go
  engine/api/cache/redis.go
  engine/api/grpc_handlers.go
  engine/api/workflow/dao_node_run_job.go
  engine/api/workflow/execute_node_job_run.go
  engine/api/workflow/execute_node_run.go
  engine/api/workflow/process.go
  engine/api/workflow/run_workflow_test.go
  engine/api/workflow/workflow_run_event.go
  engine/api/workflow_queue.go
  engine/hooks/dao.go
  engine/hooks/hooks_handlers.go
  engine/hooks/hooks_router.go
  engine/hooks/scheduler.go
  engine/hooks/tasks.go
  engine/vcs/github/client_event.go
  engine/worker/take_workflow_node_run_job.go
  sdk/hooks.go
Labels: hotfix, review

#2589 doc: header on POST /login
  docs/content/cli/api/_index.md
Labels: review

#2590 fix (engine): resync lock
  engine/api/grpc_handlers.go
  engine/api/workflow_queue.go
Labels: review

#2591 feat (worker): new timeout 120s
  engine/api/workflow/process.go
  engine/worker/cmd_update.go
  engine/worker/init.go
  sdk/cdsclient/client.go
Labels: review

#2592 fix (worker): timeout 360s
  engine/worker/cmd_update.go
  engine/worker/init.go
  sdk/cdsclient/client.go
Labels: review

#2596 fix (service/hooks): ProcessingTimestamp==0 : todo
  engine/hooks/hooks_handlers.go
Labels: review

#2594 doc: requirement network access
  docs/content/workflows/pipelines/requirements/_index.md
  docs/content/workflows/pipelines/requirements/network_access/_index.md
Labels: next

#2597 fix(ui): fix version polling time
  ui/src/assets/worker/web/version.js
Labels: review

#2598 fix (worker): retry after 15s
  engine/worker/take_workflow_node_run_job.go
Labels: review

#2599 fix(api): fix purge for empty pure tags
  engine/api/workflow/dao_run.go
Labels: review

#2600 fix(api): filter purge for empty pure tags
  engine/api/workflow/dao.go
Labels: review

#2601 fix (engine): remove fixme - git branch
  engine/api/grpc_handlers.go
  engine/api/workflow_queue.go
Labels: review

#2602 fix(ui): fix bad run node
  ui/src/app/shared/workflow/node/run/node.run.param.component.ts
  ui/src/app/views/workflow/sidebar/run/node/workflow.sidebar.run.node.component.ts
Labels: review

#2604 fix(api): quick fix on db to add ctx on limited handlers
  engine/api/api.go
  engine/api/workflow/resync_workflow.go
  engine/api/workflow_queue.go
Labels: review

#2603 doc: fix typo in redis sentinel configuration
  engine/api/api.go
  engine/hooks/types.go
  engine/repositories/types.go
Labels: next

#2605 fix(ui): fix run join and add loader
  ui/src/app/shared/workflow/join/workflow.join.component.ts
  ui/src/app/shared/workflow/join/workflow.join.html
  ui/src/app/shared/workflow/join/workflow.join.scss
  ui/src/app/views/workflow/graph/workflow.graph.component.ts
Labels: review

#2607 fix (engine): log postLog + add prj in logs
  engine/api/grpc_handlers.go
  engine/api/permission.go
  engine/api/workflow/workflow_run_event.go
  engine/api/workflow_queue.go
  engine/api/workflow_run.go
Labels: review

#2608 fix (vcs/gitlab): timeout & repoFullname
  engine/vcs/gitlab/client_repos.go
  engine/vcs/gitlab/oauth_consumer.go
Labels: review

#2614 feat(api): add load options for node run and tests
  engine/api/workflow/dao_node_run.go
  engine/api/workflow/dao_run.go
  engine/api/workflow/execute_node_job_run.go
  engine/api/workflow/execute_node_run.go
  engine/api/workflow/process.go
  engine/api/workflow/process_parameters.go
  engine/api/workflow/resync_workflow.go
  engine/api/workflow/run_workflow.go
  engine/api/workflow/run_workflow_test.go
  engine/api/workflow/workflow_run_event.go
  engine/api/workflow_application.go
  engine/api/workflow_queue.go
  engine/api/workflow_queue_artifact.go
  engine/api/workflow_queue_test.go
  engine/api/workflow_run.go
  engine/api/workflow_run_test.go
  engine/api/workflow_trigger.go
Labels: review

#2616 fix(sdk): add retry on artifact/url
  sdk/cdsclient/client_queue.go
Labels: review

#2617 fix: avoid node run duplication
  engine/sql/090_unique_subnum.sql
Labels: review
