Repository ovh/cds, pull requests merged in 2018-11, with the labels that each got.

#3535 fix(sdk): don't export empty metadata in workflow as code
  sdk/exportentities/workflow.go
Labels: ascode, bug

#3528 refacto(api): workflow notification code and remove old workflows notifications business code
  engine/api/api_routes.go
  engine/api/application.go
  engine/api/application/dao.go
  engine/api/application/dao_dependencies.go
  engine/api/application_pipeline.go
  engine/api/event/publish.go
  engine/api/notification.go
  engine/api/notification/user.go
  engine/api/project_notif.go
  engine/api/project_notif_test.go
  engine/api/workflow/dao_notification.go
  engine/api/workflow/dao_test.go
  sdk/notif.go
  sdk/workflow.go
Labels: api, refactor

#3530 fix: wait loading application before testing nul
  engine/api/workflow/hook.go
Labels: ready-to-merge

#3533 fix(api): take first value when no default value in pipeline parameter list (close #3520)
  engine/api/workflow/process.go
  ui/package.json
Labels: ready-to-merge

#3547 fix(plugin): fix duplicate logs from plugins
  contrib/grpcplugins/action/venom/main.go
  contrib/grpcplugins/deployment/arsenal/Makefile
  engine/worker/builtin.go
  engine/worker/builtin_deploy_application.go
  engine/worker/main.go
  engine/worker/requirement.go
  engine/worker/run_plugin.go
  go.sum
  sdk/grpcplugin/actionplugin/actionplugin.pb.go
  sdk/grpcplugin/actionplugin/actionplugin.proto
  sdk/grpcplugin/actionplugin/nodejs/README.md
  sdk/grpcplugin/actionplugin/nodejs/actionplugin_grpc_pb.js
  sdk/grpcplugin/actionplugin/nodejs/sdk.js
  sdk/grpcplugin/grpcplugin.go
Labels: hotfix, worker

#3518 fix(api): import pipeline error details
  docs/content/contribute/error_management.md
  engine/api/pipeline/pipeline_action.go
  engine/api/pipeline/pipeline_importer.go
  engine/api/pipeline_import.go
  sdk/error.go
  sdk/error_test.go
  sdk/messages.go
Labels: ascode, bug, ready-to-merge

#3562 fix(api): report could be nil
  engine/api/router_middleware.go
  engine/api/workflow/execute_node_job_run.go
  engine/api/workflow/resync_workflow.go
  engine/api/workflow/workflow_run_event.go
Labels: api, bug

#3552 fix(api): merge multiple payload (close #3550)
  engine/api/workflow/process.go
  sdk/parameter.go
  sdk/parameter_test.go
Labels: api, bug, ready-to-merge

#3556 fix(ui): display all logs after a click when job is running
  ui/angular.json
  ui/package.json
  ui/src/app/views/workflow/run/node/pipeline/step/step.log.component.ts
  ui/src/tsconfig.lint.json
Labels: bug, ready-to-merge, ui

#3561 fix(api): delete binary capabilities from worker model when it doesn't exist (close #3557)
  engine/api/cache/cache.go
  engine/api/cache/redis.go
  engine/api/worker.go
  engine/api/worker/model.go
  engine/api/worker/worker.go
  engine/api/workflow_queue_test.go
Labels: api, bug

#3511 fix(api): fix heartbeat of worker and restart worker if crash happened
  engine/api/api.go
  engine/api/worker/heartbeat.go
  engine/api/worker/init.go
  engine/api/worker/model_capabilities.go
  engine/api/worker/worker.go
  engine/api/workflow/dao_node_run_job.go
  engine/api/workflow/execute_node_job_run.go
  engine/api/workflow/heartbeat.go
  engine/api/workflow/init.go
Labels: bug

#3576 fix(api): Load WorkerModel
  engine/api/worker/gorp_model.go
  sdk/worker.go
Labels: api, bug, hotfix

#3546 feat(api, sdk, ui): notifications as code
  engine/api/notification.go
  engine/api/notification/permission.go
  engine/api/notification/user.go
  engine/api/workflow/dao_test.go
  engine/api/workflow/workflow_exporter.go
  sdk/common.go
  sdk/error.go
  sdk/exportentities/workflow.go
  sdk/exportentities/workflow_notif.go
  sdk/exportentities/workflow_notif_test.go
  sdk/exportentities/workflow_test.go
  sdk/notif.go
  ui/src/app/model/notification.model.ts
  ui/src/app/service/notification/notification.service.ts
  ui/src/app/views/workflow/show/notification/form/workflow.notification.form.component.ts
  ui/src/app/views/workflow/show/notification/list/workflow.notification.list.component.ts
  ui/src/app/views/workflow/show/notification/list/workflow.notification.list.html
Labels: api, ascode

#3582 feat(ui): ansi and html in logs is now displayed (#3166)
  ui/angular.json
  ui/package.json
  ui/src/app/shared/pipes/safeHtml.pipe.spec.ts
  ui/src/app/shared/pipes/safeHtml.pipe.ts
  ui/src/app/views/workflow/run/node/pipeline/step/step.log.component.ts
  ui/src/app/views/workflow/run/node/pipeline/step/step.log.html
  ui/src/assets/i18n/en.json
  ui/src/assets/i18n/fr.json
Labels: feature

#3614 fix(ui): join display on macOS + chromium
  ui/src/app/shared/workflow/wnode/join/node.join.html
  ui/src/app/shared/workflow/wnode/join/node.join.scss
Labels: ready-to-merge

#3616 feat(worker): support volkswagen
  engine/worker/builtin_script.go
Labels: ready-to-merge

#3618 feat(api,ui,worker): add serve static files (close #3567)
  docs/content/workflows/pipelines/actions/builtin/serve-static-files.md
  docs/static/images/workflows.pipelines.actions.builtin.serve-static-files-job.png
  docs/static/images/workflows.pipelines.actions.builtin.serve-static-files-logs.png
  docs/static/images/workflows.pipelines.actions.builtin.serve-static-files-tab.png
  engine/api/action/builtin.go
  engine/api/api_routes.go
  engine/api/objectstore/fs.go
  engine/api/objectstore/objectstore.go
  engine/api/objectstore/ssh.go
  engine/api/objectstore/swift.go
  engine/api/workflow/dao_node_run.go
  engine/api/workflow/dao_run.go
  engine/api/workflow/dao_staticfiles.go
  engine/api/workflow/dao_staticfiles_test.go
  engine/api/workflow/gorp_model.go
  engine/api/workflow_queue_staticfiles.go
  engine/api/workflow_queue_test.go
  engine/api/workflow_run.go
  engine/sql/139_static_files.sql
  engine/worker/builtin.go
  engine/worker/builtin_serve_static_files.go
  engine/worker/cmd_cache.go
  sdk/action_script.go
  sdk/artifact.go
  sdk/cache.go
  sdk/cdsclient/client.go
  sdk/cdsclient/client_queue.go
  sdk/cdsclient/client_repositories_manager.go
  sdk/cdsclient/interface.go
  sdk/exportentities/action.go
  sdk/exportentities/pipeline.go
  sdk/exportentities/pipeline_test.go
  sdk/static_files.go
  sdk/workflow_run.go
  tests/fixtures/ITSCWRKFLW7/ITSCWRKFLW7.yml
  tests/fixtures/ITSCWRKFLW7/serve.pip.yml
  tests/sc_workflow_run_simple_serve.yml
  ui/src/app/model/workflow.run.model.ts
  ui/src/app/views/workflow/run/node/artifact/artifact.list.component.ts
  ui/src/app/views/workflow/run/node/artifact/artifact.list.html
  ui/src/app/views/workflow/run/node/node.html
  ui/src/assets/i18n/en.json
  ui/src/assets/i18n/fr.json
Labels: action, api, engine, feature, ui, worker

#3571 Add some new features for debpacker
  cli/cdsctl/Makefile
  engine/Makefile
  engine/worker/Makefile
  tools/debpacker/.gitignore
  tools/debpacker/Makefile
  tools/debpacker/debpacker.go
  tools/debpacker/debpacker_test.go
  tools/debpacker/main.go
  tools/debpacker/tmpl.go
  tools/debpacker/writer.go
  tools/debpacker/writer_test.go
  tools/os-ansible-inventory/Makefile
Labels: feature, ready-to-merge, tools

#3649 feat(ui): add sentry support
  ui/package.json
  ui/src/app/app.component.ts
  ui/src/app/app.module.ts
  ui/src/environments/environment.prod.ts
  ui/src/environments/environment.test.ts
  ui/src/environments/environment.ts
Labels: ui

#3659 fix(api): run manual join + do not run join when parent failed
  engine/api/workflow/process_node.go
  engine/api/workflow/process_start.go
  ui/src/app/shared/workflow/sidebar/run-node/workflow.sidebar.run.node.component.ts
Labels: ready-to-merge
