Repository ovh/cds, pull requests merged in 2018-12, with the labels that each got.

#3671 fix(ui): fix some issues found in sentry
  ui/src/app/app.service.ts
  ui/src/app/shared/workflow/sidebar/run-node/workflow.sidebar.run.node.component.ts
Labels: bug, ui

#3673 feat(api,ui): enable run condition for join and fork
  engine/api/workflow/process_node.go
  sdk/exportentities/workflow.go
  sdk/exportentities/workflow_test.go
  sdk/workflow.go
  sdk/workflow_data.go
  sdk/workflow_node.go
  ui/src/app/shared/workflow/sidebar/edit-node/sidebar.edit.html
Labels: ready-to-merge

#3731 fix(ui): put toolbar over the logs
  ui/src/app/views/workflow/run/node/pipeline/step/step.log.html
  ui/src/app/views/workflow/run/node/pipeline/step/step.log.scss
Labels: ui
