Repository ovh/cds, pull requests merged in 2018-02, with the labels that each got.

#2198 test (it): remove deprecated project list
  tests/cli_project.yml
  tests/clictl_user.yml
Labels: review

#2199 refactor (api): sse - db access in lock
  engine/api/api_routes.go
  engine/api/lastupdate.go
  engine/api/permission.go
  engine/api/router_util.go
Labels: review

#2200 fix (variables): use helpers in worker
  docs/content/hatchery/_index.md
  docs/content/workflows/pipelines/variables.md
  engine/worker/run.go
Labels: review

#2204 fix (sdk): JSON marshall for UserPermissions
  Gopkg.lock
  engine/api/environment/environment.go
  engine/api/permission.go
  engine/api/permission/permission.go
  engine/api/permission_test.go
  engine/api/router_persmission.go
  sdk/requirement.go
  sdk/requirement_easyjson.go
  sdk/user.go
  sdk/user_easyjson.go
  sdk/worker.go
  sdk/worker_easyjson.go
  vendor/github.com/mailru/easyjson/LICENSE
  vendor/github.com/mailru/easyjson/buffer/pool.go
  vendor/github.com/mailru/easyjson/helpers.go
  vendor/github.com/mailru/easyjson/jlexer/bytestostr.go
  vendor/github.com/mailru/easyjson/jlexer/bytestostr_nounsafe.go
  vendor/github.com/mailru/easyjson/jlexer/error.go
  vendor/github.com/mailru/easyjson/jlexer/lexer.go
  vendor/github.com/mailru/easyjson/jwriter/writer.go
  vendor/github.com/mailru/easyjson/raw.go
Labels: review

#2207 fix(ui): fix add pipeline after trigger in specific case
  ui/src/app/views/workflow/sidebar/edit/node/workflow.sidebar.edit.node.component.ts
Labels: bug, review

#2203 fix(api): update last execution time and change default tab for application in ui
  engine/api/workflow/process.go
  ui/src/app/views/application/show/application.component.ts
Labels: review

#2208 fix (sdk): interpolate with unknown function
  sdk/interpolate/interpolate.go
  sdk/interpolate/interpolate_test.go
  tests/clictl_version.yml
Labels: review

#2210 feat (api): support lua regex
  Gopkg.lock
  docs/content/workflows/design/run-conditions.md
  sdk/luascript/luascript.go
  sdk/luascript/luascript_test.go
  vendor/github.com/yuin/gluare/LICENSE
  vendor/github.com/yuin/gluare/gluare.go
Labels: review

#2212 fix (api): ignore vcs hooks deletion if we lost their data
  engine/api/repositoriesmanager/repositories_manager.go
Labels: review

#2215 fix (worker): replace - with _ in expored env
  engine/worker/builtin_script.go
Labels: review

#2214 feat (sdk): allow empty {{.cds.app.foo|default ''}}
  docs/content/workflows/pipelines/variables.md
  sdk/interpolate/interpolate.go
  sdk/interpolate/interpolate_helper.go
  sdk/interpolate/interpolate_test.go
Labels: review

#2217 fix (api): workflow import bad request
  engine/api/workflow/workflow_importer.go
Labels: review

#2225 fix (contrib/actions): gobuild & interpolate var
  contrib/actions/cds-go-build.hcl
Labels: review

#2228 fix (api): better redis retry
  engine/api/cache/redis.go
Labels: review

#2227 fix(sdk): export checkout application as code
  engine/api/action/builtin.go
  engine/worker/builtin.go
  sdk/action.go
  sdk/action_script.go
  sdk/exportentities/action.go
  sdk/exportentities/pipeline.go
  sdk/exportentities/pipeline_test.go
Labels: review

#2229 fix(ui): change reference of existing tag to rerender into select
  ui/src/app/views/workflow/show/admin/workflow.admin.component.html
  ui/src/app/views/workflow/show/admin/workflow.admin.component.ts
Labels: review

#2219 fix(api): recreate hooks after import
  engine/api/workflow/hook.go
  sdk/workflow_hook.go
Labels: review

#2230 feat(api): workflow as code wip
  engine/api/ascode.go
  engine/api/ascode_test.go
  engine/api/group/public.go
  engine/api/workflow/workflow_parser.go
  engine/api/workflow/workflow_parser_test.go
  engine/api/workflow_import.go
  engine/repositories/processor_checkout.go
  engine/repositories/processor_loadfiles.go
  engine/sql/079_workflow_as_code.sql
  sdk/repositories_operation.go
  sdk/workflow.go
Labels: review

#2234 feat(hooks): add git poller
  docs/content/workflows/design/hooks/_index.md
  docs/content/workflows/design/hooks/git-poller.md
  engine/api/api_routes.go
  engine/api/hook.go
  engine/api/workflow/dao_hook.go
  engine/api/workflow/dao_hook_model.go
  engine/api/workflow/dao_node.go
  engine/api/workflow/dao_node_run.go
  engine/api/workflow/hook.go
  engine/api/workflow_hook_test.go
  engine/hooks/poller.go
  engine/hooks/scheduler.go
  engine/hooks/tasks.go
  sdk/cdsclient/client_hook.go
  sdk/cdsclient/http.go
  sdk/cdsclient/interface.go
  sdk/repositories_manager.go
  ui/src/app/views/workflow/run/node/summary/run.summary.html
Labels: review

#2237 fix (api): new signature writeJSON
  engine/api/hook.go
Labels: review

#2235 fix (api): remove unused key "secret" in db section
  engine/api/api.go
  engine/api/database/cli.go
Labels: review

#2238 fix(api): send notifications to initiator when it comes from a hook
  engine/api/notification/user.go
  engine/api/workflow/run_workflow.go
Labels: review

#2241 feat(api): put the node name of the current node run inside variables
  engine/api/workflow/process.go
Labels: review

#2243 fix(api): log error if you can't delete hook from vcs but don't return error
  engine/api/workflow/hook.go
Labels: review

#2244 fix (api): mail tls
  cli/cds/application/variable.go
  cli/cds/environment/variable.go
  cli/cds/project/variable.go
  engine/api/group/public.go
  engine/api/mail/mail.go
  engine/config.go
  sdk/error.go
  sdk/messages.go
Labels: review

#2236 feat (worker): worker download
  engine/worker/cmd_download.go
  engine/worker/cmd_server.go
  engine/worker/main.go
Labels: review

#2246 fix(hooks): fix stop task for poller
  engine/hooks/hooks_handlers.go
  engine/hooks/tasks.go
Labels: bug, review

#2253 fix (sdk): build with osx / go1.10
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/docker/docker-credential-helpers/credentials/error.go
  vendor/github.com/docker/docker-credential-helpers/credentials/version.go
  vendor/github.com/docker/docker-credential-helpers/osxkeychain/osxkeychain_darwin.go
  vendor/github.com/docker/docker-credential-helpers/osxkeychain/url_go18.go
  vendor/github.com/docker/docker-credential-helpers/osxkeychain/url_non_go18.go
Labels: review

#2254 fix (worker): extract .git.* only if git clone app
  engine/worker/builtin_gitclone.go
Labels: review

#2202 feat (cli): shell command
  Gopkg.lock
  Gopkg.toml
  cli/cdsctl/admin.go
  cli/cdsctl/health.go
  cli/cdsctl/main.go
  cli/cdsctl/project.go
  cli/cdsctl/shell.go
  cli/cdsctl/version.go
  cli/cdsctl/workflow_advanced.go
  cli/cobra.go
  sdk/application.go
  sdk/environment.go
  sdk/group.go
  sdk/status.go
  sdk/util.go
  sdk/worker.go
  vendor/github.com/chzyer/readline/LICENSE
  vendor/github.com/chzyer/readline/ansi_windows.go
  vendor/github.com/chzyer/readline/complete.go
  vendor/github.com/chzyer/readline/complete_helper.go
  vendor/github.com/chzyer/readline/complete_segment.go
  vendor/github.com/chzyer/readline/history.go
  vendor/github.com/chzyer/readline/operation.go
  vendor/github.com/chzyer/readline/password.go
  vendor/github.com/chzyer/readline/rawreader_windows.go
  vendor/github.com/chzyer/readline/readline.go
  vendor/github.com/chzyer/readline/remote.go
  vendor/github.com/chzyer/readline/runebuf.go
  vendor/github.com/chzyer/readline/runes.go
  vendor/github.com/chzyer/readline/search.go
  vendor/github.com/chzyer/readline/std.go
  vendor/github.com/chzyer/readline/std_windows.go
  vendor/github.com/chzyer/readline/term.go
  vendor/github.com/chzyer/readline/term_bsd.go
  vendor/github.com/chzyer/readline/term_linux.go
  vendor/github.com/chzyer/readline/term_solaris.go
  vendor/github.com/chzyer/readline/term_unix.go
  vendor/github.com/chzyer/readline/term_windows.go
  vendor/github.com/chzyer/readline/terminal.go
  vendor/github.com/chzyer/readline/utils.go
  vendor/github.com/chzyer/readline/utils_unix.go
  vendor/github.com/chzyer/readline/utils_windows.go
  vendor/github.com/chzyer/readline/vim.go
  vendor/github.com/chzyer/readline/windows_api.go
Labels: review

#2259 fix(ui): open new tab for worker models settings
  ui/src/app/shared/requirements/form/requirements.form.html
Labels: bug, review

#2261 fix (ui): don't always display repo poller #2258
  engine/api/workflow_hook.go
Labels: review

#2262 feat (cdsctl): cdsctl shell speed nav and find cmd
  cli/cdsctl/shell.go
  engine/api/api_routes.go
  engine/api/navbar.go
  engine/api/navbar/navbar.go
  engine/api/navbar_test.go
  sdk/cdsclient/client_navbar.go
  sdk/cdsclient/interface.go
  sdk/navbar.go
  ui/src/app/service/navbar/navbar.service.ts
Labels: review

#2263 test(api): fix tu about workflow hook
  engine/api/workflow_hook_test.go
Labels: review

#2264 tests (it): sleep after run
  cli/cobra.go
Labels: review

#2250 feat(ui): add hook logs view
  engine/api/workflow.go
  engine/hooks/hooks_handlers.go
  engine/hooks/tasks.go
  sdk/hooks.go
  ui/package-lock.json
  ui/package.json
  ui/src/app/model/workflow.hook.model.ts
  ui/src/app/model/workflow.model.ts
  ui/src/app/service/hook/hook.service.ts
  ui/src/app/shared/modal/delete/delete.component.ts
  ui/src/app/shared/modal/delete/delete.html
  ui/src/app/shared/modal/delete/delete.scss
  ui/src/app/shared/shared.module.ts
  ui/src/app/shared/workflow/node/hook/details/hook.details.component.html
  ui/src/app/shared/workflow/node/hook/details/hook.details.component.scss
  ui/src/app/shared/workflow/node/hook/details/hook.details.component.ts
  ui/src/app/shared/workflow/node/hook/form/hook.form.component.ts
  ui/src/app/shared/workflow/node/hook/form/hook.form.html
  ui/src/app/shared/workflow/node/hook/hook.component.ts
  ui/src/app/shared/workflow/node/hook/hook.html
  ui/src/app/shared/workflow/node/hook/hook.scss
  ui/src/app/shared/workflow/node/workflow.node.component.ts
  ui/src/app/views/workflow/run/node/pipeline/step/step.log.html
  ui/src/app/views/workflow/sidebar/edit/hook/workflow.sidebar.hook.component.html
  ui/src/app/views/workflow/sidebar/edit/hook/workflow.sidebar.hook.component.scss
  ui/src/app/views/workflow/sidebar/edit/hook/workflow.sidebar.hook.component.ts
  ui/src/app/views/workflow/sidebar/edit/join/workflow.sidebar.edit.join.component.html
  ui/src/app/views/workflow/sidebar/edit/join/workflow.sidebar.edit.join.component.scss
  ui/src/app/views/workflow/sidebar/edit/node/workflow.sidebar.edit.node.component.html
  ui/src/app/views/workflow/sidebar/edit/node/workflow.sidebar.edit.node.component.scss
  ui/src/app/views/workflow/sidebar/edit/workflow.sidebar.edit.component.html
  ui/src/app/views/workflow/sidebar/edit/workflow.sidebar.edit.component.ts
  ui/src/app/views/workflow/sidebar/run/hook/workflow.sidebar.run.hook.component.html
  ui/src/app/views/workflow/sidebar/run/hook/workflow.sidebar.run.hook.component.scss
  ui/src/app/views/workflow/sidebar/run/hook/workflow.sidebar.run.hook.component.ts
  ui/src/app/views/workflow/sidebar/run/list/workflow.sidebar.run.component.html
  ui/src/app/views/workflow/workflow.component.ts
  ui/src/app/views/workflow/workflow.html
  ui/src/app/views/workflow/workflow.module.ts
  ui/src/app/views/workflow/workflow.routing.ts
  ui/src/assets/i18n/en.json
  ui/src/assets/i18n/fr.json
Labels: review

#2252 feat(hatchery): add spawn info when no hatchery can spawn a worker for this job
  engine/api/api_routes.go
  engine/api/hatchery.go
  engine/api/hatchery/hatchery.go
  engine/api/workflow/dao_node_run_job.go
  engine/api/workflow/execute_node_job_run.go
  engine/api/workflow_queue.go
  engine/sql/080_workflow_node_run_job_spawn_attempts.sql
  sdk/cdsclient/client_hatchery.go
  sdk/cdsclient/client_queue.go
  sdk/cdsclient/interface.go
  sdk/hatchery/hatchery.go
  sdk/hatchery/register.go
  sdk/messages.go
  sdk/workflow_run.go
Labels: review

#2255 feat: migration from key variable to sshkey
  engine/api/api.go
  engine/api/application/dao.go
  engine/api/application/dao_dependencies.go
  engine/api/environment/environment.go
  engine/api/migrate/key.go
  ui/src/app/shared/variable/value/variable.value.html
  ui/src/app/views/project/show/project.component.ts
Labels: review

#2267 fix(ui): fix refresh ui log hooks
  ui/src/app/views/workflow/sidebar/edit/hook/workflow.sidebar.hook.component.ts
  ui/src/app/views/workflow/sidebar/run/hook/workflow.sidebar.run.hook.component.ts
Labels: review

#2268 fix(api): add better error handling for hooks and improve hatchery spawn attempts
  engine/hooks/tasks.go
  sdk/hatchery/hatchery.go
  sdk/hatchery/register.go
Labels: bug, review

#2266 fix(ui): add pattern of workflow name in UI
  ui/src/app/views/workflow/add/workflow.add.component.ts
  ui/src/app/views/workflow/add/workflow.add.html
  ui/src/app/views/workflow/add/workflow.add.scss
  ui/src/assets/i18n/en.json
  ui/src/assets/i18n/fr.json
Labels: review

#2272 fix(ui): fix select on join
  ui/src/app/views/workflow/workflow.component.ts
Labels: review

#2269 fix (api): add index to load logs
  engine/sql/081_idx_logs.sql
Labels: review

#2276 chore(docker-compose): use dictionary yaml for environment in comments
  docker-compose.yml
Labels: next

#2251 fix(api): return error if two model are selected in requirements
  engine/api/action/action.go
  sdk/error.go
  ui/src/app/shared/action/action.component.ts
  ui/src/app/shared/action/action.html
  ui/src/app/shared/requirements/form/requirements.form.component.ts
  ui/src/app/shared/requirements/form/requirements.form.html
  ui/src/assets/i18n/en.json
  ui/src/assets/i18n/fr.json
Labels: review

#2280 fix(api): fix permission on get token list for user
  engine/api/token/token.go
  engine/api/user.go
Labels: review

#2287 fix (api): load and encode key on workflow resync
  engine/api/workflow/resync_workflow.go
Labels: review

#2277 fix(ui): fix account verify modal and don't display permissions
  ui/src/app/service/user/user.service.ts
  ui/src/app/views/account/verify/verify.component.ts
  ui/src/app/views/account/verify/verify.html
Labels: review

#2288 fix(api): flush lastupdate buffer by default
  engine/api/lastupdate.go
Labels: review

#2290 feat(hooks): add hook disable configuration
  engine/api/workflow/run_workflow.go
  engine/hooks/hooks.go
  engine/hooks/types.go
Labels: review

#2292 fix(cli): search workflow wrong limit
  cli/cdsctl/workflow.go
Labels: review

#2291 feat(api): fetch commit infos for bitbucket repository webhook to let user check git.message in run conditions
  engine/api/workflow/process.go
Labels: review

#2286 feat(api): resync noderun vcs statuses
  engine/api/repositoriesmanager/events.go
  engine/api/repositoriesmanager/repositories_manager.go
  engine/api/workflow/process.go
  engine/api/workflow/workflow_run_event.go
  engine/vcs/bitbucket/client_status.go
  engine/vcs/bitbucket/client_status_test.go
  engine/vcs/bitbucket/types.go
  engine/vcs/github/client_status.go
  engine/vcs/gitlab/client_status.go
  engine/vcs/gitlab/gitlab.go
  engine/vcs/vcs_handlers.go
  engine/vcs/vcs_handlers_test.go
  engine/vcs/vcs_router.go
  sdk/repositories_manager.go
  sdk/vcs.go
Labels: review

#2295 fix: add debug log
  engine/api/workflow/dao.go
  engine/api/workflow/dao_node.go
Labels: review

#2274 doc (vcs): upgrade doc with new conf file
  cli/cdsctl/shell.go
  cli/cdsctl/workflow_import.go
  cli/cdsctl/workflow_push.go
  cli/cdsctl/workflow_stop.go
  docs/content/hosting/ready-to-run/docker-compose.md
  docs/content/hosting/repositories-manager/_index.md
  docs/content/hosting/repositories-manager/bitbucket.md
  docs/content/hosting/repositories-manager/github.md
  docs/content/hosting/repositories-manager/gitlab.md
  engine/vcs/types.go
Labels: review

#2294 fix(api): workflow as code header
  cli/cdsctl/workflow_as_code.go
  cli/cdsctl/workflow_pull.go
  cli/cdsctl/workflow_push.go
  engine/api/ascode.go
  engine/api/router.go
  engine/api/workflow_import.go
  sdk/cdsclient/client_import.go
  sdk/request.go
Labels: review

#2296 fix(ui): autocompletion in advanced run conditions don't autocomplete correctly with git_... #2278
  ui/resources/cds-hint.js
Labels: bug, review

#2299 fix(api): application migration condition operator
  engine/api/migrate/migrate_workflow.go
Labels: review

#2300 test(cli): fix workflow push tests
  cli/cdsctl/workflow_push.go
  tests/sc_workflow_create_run_join.yml
Labels: review

#2293 fix(api): fix path escape
  engine/api/services/http.go
  engine/vcs/github/http.go
  engine/vcs/vcs_handlers.go
Labels: review

#2297 feat (api): allow using workflow.* var in stage conditions
  sdk/stage.go
Labels: review

#2298 fix(api): workflow status compute
  engine/api/workflow/dao_run.go
  engine/api/workflow/process.go
Labels: review

#2306 fix(api): remove swift verbose logs
  engine/api/objectstore/swift.go
Labels: review

#2307 fix (api): update some logs level
  engine/api/workflow/dao_run.go
  engine/api/workflow_queue.go
  engine/hatchery/local/local.go
  engine/hatchery/marathon/marathon.go
  engine/hatchery/openstack/openstack.go
  engine/hatchery/openstack/spawn.go
  engine/hatchery/swarm/swarm.go
Labels: review

#2308 fix (api): found ref must return good pointer
  engine/api/workflow/dao_join.go
Labels: review

#2303 fix (api): hide vcs http password
  engine/api/workflow/execute_node_job_run.go
  engine/api/workflow/process_parameters.go
Labels: review

#2301 fix(ui): refresh display hook when add or remove one
  ui/src/app/views/workflow/graph/workflow.graph.component.ts
Labels: review

#2305 fix(vcs): remove verbose setStatus logs
  engine/vcs/bitbucket/client_status.go
  engine/vcs/github/client_status.go
Labels: review

#2309 feat (hatchery): update log level
  engine/hatchery/swarm/swarm.go
Labels: review

#2311 fix(api): key type
  engine/api/migrate/key.go
Labels: review

#2284 feat (plugin/marathon): add new labels
  contrib/plugins/plugin-marathon/marathon.go
Labels: review

#2260 feat(api): add kafka platform for hook provider
  Gopkg.lock
  Gopkg.toml
  engine/api/api.go
  engine/api/api_routes.go
  engine/api/platform.go
  engine/api/platform/dao_model.go
  engine/api/platform/gorp_model.go
  engine/api/project.go
  engine/api/project/dao.go
  engine/api/project/dao_dependencies.go
  engine/api/project/dao_platform.go
  engine/api/project/gorp_model.go
  engine/api/project_platform.go
  engine/api/project_platform_test.go
  engine/api/workflow/dao_hook_model.go
  engine/api/workflow/hook.go
  engine/api/workflow_hook.go
  engine/hooks/hooks_handlers.go
  engine/hooks/kafka.go
  engine/hooks/tasks.go
  engine/sql/082_platform.sql
  sdk/cdsclient/client_project_kafka.go
  sdk/cdsclient/interface.go
  sdk/hook.go
  sdk/hooks.go
  sdk/platform.go
  sdk/project.go
  sdk/workflow_hook.go
  ui/src/app/app.service.ts
  ui/src/app/model/platform.model.ts
  ui/src/app/model/project.model.ts
  ui/src/app/model/workflow.model.ts
  ui/src/app/service/platform/platform.service.ts
  ui/src/app/service/project/project.resolver.ts
  ui/src/app/service/project/project.service.ts
  ui/src/app/service/project/project.store.ts
  ui/src/app/service/services.module.ts
  ui/src/app/shared/workflow/node/hook/form/hook.form.html
  ui/src/app/views/project/project.module.ts
  ui/src/app/views/project/show/platforms/form/platform.form.component.ts
  ui/src/app/views/project/show/platforms/form/project.platform.form.html
  ui/src/app/views/project/show/platforms/form/project.platform.form.scss
  ui/src/app/views/project/show/platforms/list/platform.list.component.ts
  ui/src/app/views/project/show/platforms/list/project.platform.list.html
  ui/src/app/views/project/show/platforms/list/project.platform.list.scss
  ui/src/app/views/project/show/platforms/project.platforms.component.ts
  ui/src/app/views/project/show/platforms/project.platforms.html
  ui/src/app/views/project/show/platforms/project.platforms.scss
  ui/src/app/views/project/show/project.html
  ui/src/assets/i18n/en.json
  ui/src/assets/i18n/fr.json
  vendor/github.com/fsamin/go-dump/encoder.go
Labels: review

#2285 fix (api): no check for removing group on default env
  engine/api/application/application_group.go
  engine/api/group/environment_group.go
  engine/sql/082_clean_env_grp.sql
  engine/sql/083_platform.sql
Labels: review

#2316 doc (vcs): how to generate keys for bitbucket
  docs/content/hosting/repositories-manager/bitbucket.md
Labels: review

#2319 fix(api): check app and env name on import
  engine/api/application/application_parser.go
  engine/api/application_import_test.go
  engine/api/environment/environment_parser.go
  engine/api/environment_import_test.go
  engine/api/workflow_import_test.go
  sdk/error.go
Labels: review

#2313 doc: add doc on kafka hook
  docs/content/introduction/concepts/_index.md
  docs/content/workflows/design/hooks/_index.md
  docs/content/workflows/design/hooks/kafka-hook.md
Labels: review

#2320 fix (api): use const in hook config
  engine/api/hook.go
  engine/api/workflow.go
  engine/api/workflow/dao_hook.go
  engine/api/workflow/dao_node.go
  engine/api/workflow/hook.go
  engine/api/workflow/workflow_importer_test.go
  engine/hooks/hooks_handlers.go
  engine/hooks/kafka.go
  engine/hooks/tasks.go
  sdk/hook.go
Labels: review
