Repository ovh/cds, pull requests merged in 2018-03, with the labels that each got.

#2329 fix (api): more logs on artifact upload err
  engine/api/workflow_queue_artifact.go
Labels: review

#2330 feat (api, hatchery): info -> debug common logs
  engine/api/error.go
  engine/hatchery/openstack/openstack.go
  engine/hatchery/openstack/spawn.go
  engine/hatchery/swarm/swarm.go
Labels: review

#2325 fix(api): improve retry on redis
  engine/api/cache/redis.go
Labels: review

#2328 fix(api,vcs): inconsistent statuses
  engine/api/workflow/workflow_run_event.go
  engine/vcs/github/client_status.go
Labels: review

#2302 fix(api): add default payload on git pollers
  engine/hooks/tasks.go
  sdk/hook.go
Labels: review

#2310 feat(api,cli): import, export action
  cli/cdsctl/action.go
  cli/cdsctl/workflow_push.go
  engine/api/action.go
  engine/api/action/action_exporter.go
  engine/api/action/builtin.go
  engine/api/action_test.go
  engine/api/api_routes.go
  engine/api/pipeline/pipeline_build.go
  engine/api/workflow/process.go
  sdk/cdsclient/client_action.go
  sdk/cdsclient/interface.go
  sdk/exportentities/action.go
  sdk/exportentities/application.go
Labels: review

#2318 feat (cds2xmpp): Detect XML in text and decide to send as HML of raw text
  contrib/uservices/cds2xmpp/service/bot.go
  contrib/uservices/cds2xmpp/service/bot_test.go
Labels: review

#2323 feat(api): import keys without values but avoid regen them
  cli/cdsctl/workflow_as_code.go
  engine/api/application/application_parser.go
  engine/api/application_import_test.go
  engine/api/environment/environment_parser.go
  engine/api/keys/parse.go
  sdk/application.go
  sdk/environment.go
  sdk/exportentities/application.go
  sdk/exportentities/environment.go
  sdk/exportentities/types.go
Labels: review

#2333 fix(api): import error management
  engine/api/environment_import.go
  engine/api/pipeline_import.go
Labels: review

#2335 fix (service/cds2xmpp): init xmlRegexp
  contrib/uservices/cds2xmpp/service/bot.go
Labels: review

#2334 fix: update workflow
  engine/api/workflow/dao.go
  engine/api/workflow/dao_join.go
  engine/api/workflow/dao_node.go
  engine/api/workflow/dao_trigger.go
  sdk/workflow.go
  ui/src/app/model/workflow.model.ts
  ui/src/app/service/workflow/workflow.service.ts
  ui/src/app/shared/workflow/node/wizard/node.wizard.html
  ui/src/app/views/workflow/add/workflow.add.html
  ui/src/app/views/workflow/graph/workflow.graph.component.ts
  ui/src/app/views/workflow/show/workflow.component.ts
Labels: review

#2336 fix(ui): change usage icon
  ui/src/app/views/application/show/application.html
  ui/src/app/views/pipeline/show/pipeline.show.html
  ui/src/app/views/workflow/show/workflow.html
Labels: review

#2339 fix (api): upload artifact - compare obj
  engine/api/workflow_queue_artifact.go
  sdk/workflow_run.go
Labels: review

#2341 feat (sdk, api, repositories): vcsserver in repositories operation
  engine/api/ascode.go
  engine/api/workflow_import.go
  sdk/repositories_operation.go
Labels: review

#2338 doc(engine): update README.md
  engine/README.md
Labels: review

#2327 feat(worker): add worker cache command
  engine/api/api_routes.go
  engine/api/cache.go
  engine/worker/cmd_cache.go
  engine/worker/cmd_server.go
  engine/worker/main.go
  sdk/cache.go
  sdk/cdsclient/client_workflow.go
  sdk/cdsclient/interface.go
  sdk/error.go
Labels: review

#2345 feat (worker): worker artifacts cmd
  engine/worker/cmd_artifacts.go
  engine/worker/cmd_server.go
  engine/worker/main.go
  sdk/workflow_run.go
Labels: review

#2346 fix(ui): put payload to read-only when you launch non root node
  ui/src/app/shared/workflow/node/run/node.run.param.component.ts
  ui/src/app/shared/workflow/node/run/node.run.param.html
  ui/src/assets/i18n/en.json
  ui/src/assets/i18n/fr.json
Labels: review

#2347 fix(ui): display value of config even if type is empty
  ui/src/app/shared/workflow/node/hook/form/hook.form.html
  ui/src/app/views/pipeline/show/workflow/pipeline.workflow.component.ts
Labels: bug, review

#2349 fix(ui): block browser autofill
  ui/src/app/views/project/show/platforms/form/project.platform.form.html
  ui/src/app/views/project/show/platforms/list/project.platform.list.html
Labels: review

#2282 fix (engine): use execGroups - worker checks wm groups
  engine/api/api.go
  engine/api/group/project_group.go
  engine/api/mon_db.go
  engine/api/permission.go
  engine/api/workflow/dao_node_run_job.go
  engine/api/workflow/execute_node_run.go
  engine/api/workflow/run_workflow_test.go
  engine/api/workflow_queue.go
  engine/api/workflow_queue_test.go
  engine/sql/084_wnrj_groups.sql
  engine/worker/builtin_script.go
  engine/worker/requirement.go
  engine/worker/run.go
  engine/worker/take_pipeline_build_job.go
  sdk/util.go
  sdk/workflow_run.go
Labels: review, rework, sql

#2343 fix(ui): add warning when user want to delete root pipeline with all childs #2206
  ui/src/app/shared/workflow/node/delete/workflow.node.delete.component.ts
  ui/src/app/shared/workflow/node/delete/workflow.node.delete.html
  ui/src/app/views/workflow/sidebar/edit/node/workflow.sidebar.edit.node.component.html
  ui/src/assets/i18n/en.json
  ui/src/assets/i18n/fr.json
Labels: review

#2351 doc: from binaries
  docs/content/hosting/ready-to-run/from-binaries.md
Labels: review

#2352 feat(repositories): support auth strategies
  Gopkg.lock
  engine/repositories/processor_checkout.go
  vendor/github.com/fsamin/go-repo/LICENSE.md
  vendor/github.com/fsamin/go-repo/cmd.go
  vendor/github.com/fsamin/go-repo/keys.go
  vendor/github.com/fsamin/go-repo/repo.go
  vendor/github.com/fsamin/go-repo/types.go
Labels: review

#2354 fix(sql): swap 082 and 083 sql files
  engine/sql/082_platform.sql
  engine/sql/083_clean_env_grp.sql
Labels: review

#2348 fix(ui): add scroll to modal hook
  ui/src/app/shared/workflow/node/hook/form/hook.form.component.ts
Labels: review

#2353 fix: use workflow run to check group
  engine/api/workflow/execute_node_run.go
Labels: review

#2357 fix: add error log
  engine/worker/cmd_cache.go
Labels: review

#2358 fix(sdk): remove timeout on worker push and pull
  sdk/cdsclient/client_workflow.go
Labels: review

#2359 fix (api): pipeline parameter
  engine/api/workflow_run.go
Labels: review

#2361 fix (sdk): cache push/pull url
  sdk/cdsclient/client_workflow.go
Labels: review

#2362 fix: interpolate erreur
  engine/api/router_persmission.go
  engine/worker/run.go
Labels: review

#2363 fix (worker): cache pull + interpolate error
  engine/api/cache.go
  engine/worker/cmd_cache.go
  engine/worker/cmd_main.go
  engine/worker/run.go
  sdk/cdsclient/client_workflow.go
Labels: review

#2367 test: worker cache command in a workflow
  tests/fixtures/ITSCWRKFLW4/ITSCWRKFLW4.yml
  tests/fixtures/ITSCWRKFLW4/tag-push-pull.pip.yml
  tests/sc_workflow_run_cache.yml
Labels: review

#2366 fix(api): workflow queue permissions
  engine/api/workflow/dao_node_run_job.go
  engine/api/workflow/run_workflow_test.go
  engine/api/workflow_export_test.go
  engine/api/workflow_group_test.go
  engine/api/workflow_queue_test.go
  engine/api/workflow_run_test.go
Labels: review

#2368 fix(api, hatchery): remove verbose error logs
  engine/api/error.go
  sdk/hatchery/register.go
Labels: review

#2370 fix(cli): timeout on pipeline run command
  cli/cds/pipeline/run.go
  tests/cli_pipeline.yml
Labels: review

#2372 test(it): fix workflow run cache
  tests/sc_workflow_run_cache.yml
Labels: review

#2371 fix (hatchery): use execGroups with wf
  sdk/hatchery/register.go
Labels: review

#2373 fix(worker): main command flags
  engine/worker/cmd_main.go
  engine/worker/cmd_register.go
  engine/worker/cmd_run.go
  engine/worker/cmd_update.go
  engine/worker/init.go
  engine/worker/main.go
  engine/worker/register.go
Labels: review

#2377 feat (engine): allow many extra keys/values logs
  engine/types.go
  sdk/hatchery/hatchery.go
  sdk/log/log.go
Labels: review

#2379 feat: add project event struct
  engine/api/project/project_variable.go
  sdk/event.go
  sdk/event_project.go
Labels: review

#2376 fix(api): workflow creation default permissions
  engine/api/workflow.go
Labels: review

#2382 fix (engine): init log
  sdk/log/log.go
Labels: review

#2383 fix(sdk): cache zero byte files shouldn't raise error
  sdk/cache.go
Labels: review

#2380 fix(api): POSTEXECUTE on stop workflow handler
  engine/api/api_routes.go
Labels: review

#2375 feat (engine,ui,hatchery): worker model restricted
  docs/content/worker/_index.md
  docs/content/worker/setup-your-worker.md
  docs/content/workflows/pipelines/requirements/_index.md
  docs/content/workflows/pipelines/requirements/service/_index.md
  docs/content/workflows/pipelines/requirements/worker-model/_index.md
  engine/api/api_routes.go
  engine/api/worker/worker.go
  engine/api/worker_model.go
  engine/sql/085_worker_model_restricted.sql
  sdk/worker.go
  sdk/worker_easyjson.go
  ui/src/app/model/worker-model.model.ts
  ui/src/app/shared/action/action.html
  ui/src/app/views/admin/admin.html
  ui/src/app/views/admin/sidebar/admin-sidebar.scss
  ui/src/app/views/project/add/project.add.html
  ui/src/app/views/settings/settings.component.html
  ui/src/app/views/settings/sidebar/settings-sidebar.scss
  ui/src/app/views/settings/user/edit/user.edit.html
  ui/src/app/views/settings/worker-model/add/worker-model.add.html
  ui/src/app/views/settings/worker-model/edit/worker-model.edit.html
  ui/src/assets/i18n/en.json
  ui/src/assets/i18n/fr.json
Labels: review

#2384 fix(api): vcsInfo compute git.url & git.http_url
  engine/api/workflow/execute_node_run.go
  engine/api/workflow/process.go
  engine/api/workflow/run_workflow.go
Labels: review

#2381 fix (hatchery/swarm): count workers started
  engine/hatchery/kubernetes/kubernetes.go
  engine/hatchery/swarm/swarm.go
  engine/hatchery/swarm/swarm_util_create_test.go
  engine/hatchery/swarm/swarm_util_get.go
  engine/hatchery/swarm/swarm_util_get_test.go
  engine/hatchery/swarm/swarm_util_kill.go
Labels: review

#2378 fix (worker): auto-update
  engine/worker/cmd_main.go
  engine/worker/cmd_update.go
  engine/worker/init.go
Labels: review

#2385 doc (worker): doc about cache
  engine/worker/cmd_cache.go
Labels: review

#2388 fix(hatchery/swarm): pull image
  engine/hatchery/swarm/swarm_util_pull.go
Labels: review

#2387 fix (ui): btn stop on waiting pipeline
  ui/src/app/views/workflow/run/node/summary/run.summary.html
Labels: review

#2389 fix(api): run the workflow with the default branch if not specified
  engine/api/workflow/execute_node_run.go
Labels: review

#2386 feat: send project event
  engine/api/api.go
  engine/api/api_routes.go
  engine/api/event/publish.go
  engine/api/event/publish_project.go
  engine/api/group/group.go
  engine/api/group/project_group.go
  engine/api/project.go
  engine/api/project/dao.go
  engine/api/project/project_variable.go
  engine/api/project_group.go
  engine/api/project_key.go
  engine/api/project_platform.go
  engine/api/project_test.go
  engine/api/project_variable.go
  engine/api/repositories_manager.go
  sdk/event_project.go
Labels: review

#2391 fix(hatchery): remove verbose log
  sdk/hatchery/register.go
Labels: review

#2392 doc (worker): add if on cache pull
  engine/worker/cmd_cache.go
Labels: review

#2395 Debug
  contrib/uservices/cds2es/process.go
Labels: review

#2394 feat: add cds2es
  contrib/uservices/cds2es/.gitignore
  contrib/uservices/cds2es/Dockerfile
  contrib/uservices/cds2es/README.md
  contrib/uservices/cds2es/config.go
  contrib/uservices/cds2es/main.go
  contrib/uservices/cds2es/process.go
Labels: review

#2393 feat(tools): debpacker init
  Gopkg.lock
  tools/debpacker/.gitignore
  tools/debpacker/Makefile
  tools/debpacker/debpacker.go
  tools/debpacker/main.go
  tools/debpacker/tmpl.go
  vendor/github.com/urfave/cli/LICENSE
  vendor/github.com/urfave/cli/app.go
  vendor/github.com/urfave/cli/category.go
  vendor/github.com/urfave/cli/cli.go
  vendor/github.com/urfave/cli/command.go
  vendor/github.com/urfave/cli/context.go
  vendor/github.com/urfave/cli/errors.go
  vendor/github.com/urfave/cli/flag.go
  vendor/github.com/urfave/cli/flag_generated.go
  vendor/github.com/urfave/cli/funcs.go
  vendor/github.com/urfave/cli/help.go
Labels: review

#2397 fix(hatchery): Entrypoint init
  engine/hatchery/swarm/swarm_util_create.go
Labels: review

#2398 fix(worker): cache error & tar with symlinks
  engine/worker/cmd_cache.go
  sdk/cache.go
Labels: review

#2399 fix (engine): column restricted on wm get
  engine/api/worker/model.go
Labels: review

#2401 feat(engine): deb package
  engine/.debpacker.yml
  engine/.gitignore
  tools/debpacker/debpacker.go
  tools/debpacker/main.go
  tools/debpacker/tmpl.go
Labels: review

#2403 fix (worker): register
  engine/worker/cmd_register.go
  engine/worker/cmd_run.go
Labels: review

#2400 fix (engine): provisioning
  engine/hatchery/marathon/types.go
  sdk/hatchery/hatchery.go
Labels: review

#2402 doc
  cli/cdsctl/workflow_as_code.go
  docs/config.toml
  docs/content/gettingstarted/_index.md
  docs/content/gettingstarted/concepts/_index.md
  docs/content/gettingstarted/concepts/job.md
  docs/content/gettingstarted/concepts/pipeline.md
  docs/content/gettingstarted/concepts/stage.md
  docs/content/gettingstarted/concepts/step.md
  docs/content/gettingstarted/firstworkflow.md
  docs/content/gettingstarted/scopes/_index.md
  docs/content/gettingstarted/scopes/application.md
  docs/content/gettingstarted/scopes/environment.md
  docs/content/gettingstarted/scopes/permissions.md
  docs/content/gettingstarted/scopes/project.md
  docs/content/introduction/concepts/_index.md
  docs/content/worker/_index.md
  docs/content/workflows/pipelines/actions/_index.md
  docs/content/workflows/pipelines/requirements/_index.md
  docs/layouts/partials/landscape.html
  docs/layouts/partials/title.html
  docs/static/css/homepage.css
  docs/static/images/getting.started.run1.png
  docs/static/images/getting.started.run2.png
  sdk/action_script.go
  sdk/exportentities/action.go
Labels: review

#2406 fix: do not override entrypoint for service requirement
  engine/hatchery/swarm/swarm.go
  engine/hatchery/swarm/swarm_util_create.go
Labels: review

#2405 doc: update screenshot service link
  docs/content/workflows/pipelines/requirements/service/example-nginx.md
  docs/content/workflows/pipelines/requirements/service/example-pg.md
  docs/static/images/tutorials_service_link_nginx_job.png
  docs/static/images/tutorials_service_link_nginx_log.png
  docs/static/images/tutorials_service_link_nginx_requirements.png
  docs/static/images/tutorials_service_link_pg_job.png
  docs/static/images/tutorials_service_link_pg_log.png
  docs/static/images/tutorials_service_link_pg_requirements.png
Labels: review

#2411 fix(api): relies session store on cache.Store
  engine/api/api.go
  engine/api/api_test.go
  engine/api/auth/auth.go
  engine/api/sessionstore/factory.go
  engine/api/sessionstore/redis.go
  engine/api/sessionstore/sessionstore.go
Labels: review

#2407 fix (api): avoid sending notif on default group
  engine/api/group.go
  engine/api/group/group.go
  engine/api/group/public.go
  engine/api/notification/permission.go
  engine/api/notification/user.go
  engine/api/permission/permission.go
  engine/api/project.go
  ui/src/app/service/group/group.service.ts
  ui/src/app/views/project/add/project.add.component.ts
Labels: review

#2409 fix(ui): add a group on a workflow
  ui/src/app/app.service.ts
  ui/src/assets/i18n/en.json
  ui/src/assets/i18n/fr.json
Labels: review

#2410 doc (uservices/cds2es): configuration file example
  contrib/uservices/cds2es/README.md
Labels: review

#2408 feat (engine): --is-uptodate flag on engine update
  cli/cdsctl/update.go
  engine/main.go
  engine/update.go
  engine/uptodate.go
  engine/worker/cmd_update.go
  sdk/cdsclient/client_download.go
  sdk/cdsclient/client_mon.go
  sdk/cdsclient/interface.go
Labels: review

#2414 fix(ui): fix edit action page
  ui/src/app/shared/action/action.component.ts
  ui/src/app/shared/action/action.html
  ui/src/app/shared/parameter/form/parameter.form.html
  ui/src/app/shared/parameter/list/parameter.component.ts
  ui/src/app/shared/parameter/list/parameter.html
Labels: review

#2326 refactor(api): DEPRECATED_GitClone migration
  engine/api/action.go
  engine/api/action/action.go
  engine/api/api.go
  engine/api/bootstrap/bootstrap.go
  engine/api/workflow/dao.go
  sdk/application.go
  sdk/project.go
Labels: review

#2416 fix(api): DEPRECATED GitClone migration
  engine/api/bootstrap/bootstrap.go
Labels: review

#2430 feat(api): disable MigrateActionDEPRECATEDGitClone by default
  engine/api/api.go
Labels: review

#2432 fix(hooks): purge orphan task executions
  engine/hooks/hooks.go
  engine/hooks/scheduler.go
Labels: review

#2434 fix (api): do not erase vcs server datas
  engine/api/project.go
Labels: review

#2443 fix(api): workflow panic recovery
  engine/api/workflow_run.go
Labels: hotfix, review

#2446 fix(api): getNodeRunBuildParameters multiError
  engine/api/workflow/process_parameters.go
Labels: hotfix, review

#2433 fix(hooks): delete ZSET member on error
  engine/api/cache/redis.go
Labels: hotfix, review

#2442 fix(api): fix delete purge
  engine/api/workflow/dao_run.go
  engine/api/workflow/init.go
Labels: hotfix, review

#2449 test: retry 10 on worker cache
  tests/sc_workflow_run_cache.yml
Labels: review

#2450 fix (ui): do not restart webworker if there is no needs
  ui/src/app/views/workflow/run/workflow.run.component.ts
Labels: review

#2447 fix (ui): manage error on 404
  ui/src/app/service/application/application.store.ts
  ui/src/app/service/logout.interceptor.service.ts
  ui/src/app/service/pipeline/pipeline.store.ts
  ui/src/app/service/workflow/workflow.store.ts
  ui/src/app/views/application/show/application.component.ts
  ui/src/app/views/pipeline/show/pipeline.show.component.ts
  ui/src/app/views/workflow/show/workflow.component.ts
Labels: review

#2429 feat: update angular + angular cli
  ui/package-lock.json
  ui/package.json
  ui/src/app/views/account/verify/verify.scss
  ui/src/tsconfig.spec.json
  ui/tslint.json
Labels: review

#2431 chore: Create PULL_REQUEST_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
Labels: review

#2422 feat (hatchery/swarm): --add-host options
  docs/content/hatchery/swarm.md
  docs/content/hosting/ready-to-run/docker-compose.md
  docs/content/workflows/pipelines/requirements/service/example-pg.md
  docs/content/workflows/pipelines/requirements/worker-model/_index.md
  docs/content/workflows/pipelines/requirements/worker-model/docker-simple.md
  docs/content/workflows/pipelines/requirements/worker-model/docker/_index.md
  docs/content/workflows/pipelines/requirements/worker-model/docker/docker-customized.md
  docs/static/images/workflows.pipelines.requirements.docker.worker-model.docker.add.png
  docs/static/images/workflows.pipelines.requirements.docker.worker-model.docker.png
  engine/hatchery/swarm/swarm.go
  engine/hatchery/swarm/swarm_util_create.go
  engine/hatchery/swarm/swarm_util_create_test.go
  engine/hatchery/swarm/swarm_util_kill.go
  engine/hatchery/swarm/swarm_util_pull.go
  engine/worker/requirement.go
  ui/src/app/views/settings/worker-model/add/worker-model.add.html
  ui/src/app/views/settings/worker-model/edit/worker-model.edit.html
  ui/src/assets/i18n/en.json
  ui/src/assets/i18n/fr.json
Labels: review

#2436 fix(api): rename workflow update hooks
  sdk/workflow_hook.go
Labels: review

#2437 fix(ui): rename app or workflow show error
  engine/api/sessionstore/sessionstore.go
  ui/src/app/shared/requirements/form/requirements.form.html
  ui/src/app/views/application/show/admin/application.admin.html
  ui/src/app/views/project/show/admin/project.admin.html
  ui/src/app/views/workflow/show/admin/workflow.admin.component.html
Labels: review

#2440 fix(cli): workflow push skip directory
  cli/cdsctl/workflow_push.go
Labels: review

#2428 feat (engine,sdk): X-CDS-Until header queue count
  cli/cdsctl/monitoring.go
  engine/api/mon_db.go
  engine/api/workflow/dao_node_run_job.go
  engine/api/workflow/run_workflow_test.go
  engine/api/workflow_queue.go
  sdk/cdsclient/client_queue.go
  sdk/cdsclient/interface.go
  sdk/workflow.go
Labels: review

#2439 fix (ui): rename workflow makes advanced tab disapeared
  ui/src/app/service/workflow/workflow.store.ts
Labels: review

#2455 fix: do not duplicate env
  ui/src/app/views/project/show/environment/form/environment.form.component.ts
Labels: review

#2457 fix (ui): query params on env usage
  ui/src/app/shared/usage/environments/usage.environments.html
Labels: review

#2456 fix (ui): workflow migration progressbar
  ui/src/app/views/project/show/admin/project.admin.component.ts
  ui/src/app/views/project/show/admin/project.admin.html
Labels: review

#2444 doc: about CDS tokens
  docs/content/cli/api/_index.md
  docs/content/cli/sdk/_index.md
  ui/src/assets/i18n/en.json
  ui/src/assets/i18n/fr.json
Labels: review

#2445 fix(api): migrate action deprecated gitclone
  engine/api/api.go
  engine/api/bootstrap/bootstrap.go
  engine/api/migrate/migrate_action.go
Labels: review

#2453 fix(worker): worker cache with symlink
  sdk/cache.go
  tests/fixtures/ITSCWRKFLW4/tag-push-pull.pip.yml
Labels: hotfix

#2452 fix: keep sidebar intact
  ui/src/app/shared/action/step/step.component.ts
  ui/src/app/shared/parameter/value/parameter.value.component.ts
  ui/src/app/shared/workflow/node/workflow.node.component.ts
  ui/src/app/views/workflow/sidebar/run/node/stage/job/job.summary.component.ts
Labels: review

#2454 test(api): add tests on purge
  engine/api/workflow/dao.go
  engine/api/workflow/dao_run.go
  engine/api/workflow/dao_run_test.go
  sdk/workflow.go
  ui/src/app/views/workflow/show/admin/workflow.admin.component.html
  ui/src/app/views/workflow/show/admin/workflow.admin.component.ts
  ui/src/assets/i18n/en.json
  ui/src/assets/i18n/fr.json
Labels: review

#2421 feat(ui): change style about navbar
  ui/package-lock.json
  ui/package.json
  ui/src/app/model/navbar.model.ts
  ui/src/app/service/project/project.service.ts
  ui/src/app/service/project/project.store.ts
  ui/src/app/views/navbar/navbar.component.ts
  ui/src/app/views/navbar/navbar.html
  ui/src/app/views/navbar/navbar.scss
  ui/src/app/views/project/list/project.list.component.html
  ui/src/app/views/project/list/project.list.component.scss
  ui/src/app/views/project/list/project.list.component.ts
  ui/src/app/views/project/project.module.ts
  ui/src/app/views/project/project.routing.ts
  ui/src/app/views/project/show/project.html
  ui/src/assets/i18n/en.json
  ui/src/assets/i18n/fr.json
  ui/src/common.scss
  ui/src/styles.scss
Labels: review

#2460 refactor: remove hcl support
  cli/cds/action/add.go
  cli/cds/environment/export.go
  cli/cds/pipeline/export.go
  cli/cds/pipeline/import.go
  cli/cdsctl/pipeline.go
  sdk/action_script_test.go
  sdk/exportentities/common.go
  sdk/exportentities/common_test.go
  sdk/exportentities/pipeline.go
  sdk/exportentities/types.go
Labels: review

#2461 doc: building cds workflow ui & cdsctl links
  cli/cds/pipeline/import.go
  docs/content/workflows/_index.md
  docs/content/workflows/pipelines/configuration-file.md
Labels: review

#2462 fix(ui): fix navbar search when the database does not contain any apps
  ui/src/app/views/navbar/navbar.component.ts
Labels: next

#2464 feat(ui): add search on list (applications, pipelines, workflows)
  ui/src/app/views/project/list/project.list.component.html
  ui/src/app/views/project/show/application/application.list.component.ts
  ui/src/app/views/project/show/application/application.list.html
  ui/src/app/views/project/show/pipeline/pipeline.list.component.ts
  ui/src/app/views/project/show/pipeline/pipeline.list.html
  ui/src/app/views/project/show/workflow/workflow.list.component.ts
  ui/src/app/views/project/show/workflow/workflow.list.html
  ui/src/assets/i18n/en.json
  ui/src/assets/i18n/fr.json
Labels: enhancement, review

#2466 fix (ui): view edit job with read only rights
  ui/src/app/shared/action/action.html
  ui/src/app/shared/action/step/step.html
  ui/src/app/shared/workflow/node/form/workflow.node.form.html
  ui/src/app/shared/workflow/node/wizard/node.wizard.html
  ui/src/app/views/application/show/workflow/trigger/trigger.html
  ui/src/app/views/pipeline/show/workflow/pipeline.workflow.html
  ui/src/app/views/pipeline/show/workflow/stage/form/pipeline.stage.form.html
Labels: review

#2458 feat(api,sdk,ui): deprecated worker models
  engine/api/worker/gorp_model.go
  engine/api/worker/model.go
  engine/sql/086_worker_model_deprecated.sql
  sdk/worker.go
  sdk/worker_easyjson.go
  ui/src/app/model/worker-model.model.ts
  ui/src/app/shared/requirements/form/requirements.form.html
  ui/src/app/shared/requirements/list/requirements.list.component.ts
  ui/src/app/shared/requirements/list/requirements.list.html
  ui/src/app/shared/requirements/list/requirements.list.scss
  ui/src/app/views/settings/worker-model/add/worker-model.add.html
  ui/src/app/views/settings/worker-model/edit/worker-model.edit.html
  ui/src/app/views/settings/worker-model/list/worker-model.list.component.ts
  ui/src/app/views/settings/worker-model/list/worker-model.list.html
  ui/src/assets/i18n/en.json
  ui/src/assets/i18n/fr.json
Labels: review

#2463 feat(ui): add feature to import pipeline with yaml from UI
  ui/src/app/service/logout.interceptor.service.ts
  ui/src/app/service/pipeline/pipeline.service.ts
  ui/src/app/service/pipeline/pipeline.store.ts
  ui/src/app/shared/button/upload/upload.button.component.ts
  ui/src/app/shared/button/upload/upload.button.html
  ui/src/app/shared/button/upload/upload.button.scss
  ui/src/app/shared/shared.module.ts
  ui/src/app/views/pipeline/add/pipeline.add.component.ts
  ui/src/app/views/pipeline/add/pipeline.add.html
  ui/src/app/views/pipeline/add/pipeline.add.scss
  ui/src/app/views/workflow/add/workflow.add.component.ts
  ui/src/app/views/workflow/add/workflow.add.html
  ui/src/assets/i18n/en.json
  ui/src/assets/i18n/fr.json
Labels: review

#2468 fix (cdsctl): action import - display err
  cli/cdsctl/action.go
Labels: review

#2435 fix(api): do not write default payload with an empty git.branch
  engine/api/api.go
  engine/api/migrate/default_payload.go
  engine/api/workflow.go
  engine/api/workflow/dao_node.go
  engine/api/workflow/execute_node_run.go
  engine/api/workflow/hook.go
  engine/api/workflow/process.go
  sdk/error.go
  sdk/workflow.go
Labels: review

#2472 refactor(ui): code format
  ui/src/app/views/workflow/add/workflow.add.html
Labels: review

#2470 fix (hook): saveTaskExecution
  engine/hooks/scheduler.go
Labels: review

#2473 fix (ui): need to set current workflow run
  ui/src/app/views/workflow/run/node/workflow.run.node.component.ts
Labels: review

#2459 feat (engine,ui): allow provisioning for restricted wm
  engine/api/migrate/default_payload.go
  engine/api/worker_model.go
  engine/api/worker_model_test.go
  ui/src/app/views/settings/worker-model/add/worker-model.add.component.ts
  ui/src/app/views/settings/worker-model/add/worker-model.add.html
  ui/src/app/views/settings/worker-model/edit/worker-model.edit.component.ts
  ui/src/app/views/settings/worker-model/edit/worker-model.edit.html
Labels: review

#2478 fix (engine): scheduler enqueue
  engine/hooks/scheduler.go
  engine/hooks/tasks.go
  engine/hooks/types.go
Labels: review

#2489 fix (ui): label on checkbox
  ui/src/app/shared/action/action.html
  ui/src/app/shared/action/step/step.component.ts
  ui/src/app/shared/action/step/step.html
  ui/src/app/views/application/show/workflow/trigger/trigger.html
  ui/src/app/views/pipeline/show/workflow/stage/form/pipeline.stage.form.html
Labels: hotfix

#2477 fix(api): do not write default payload with an empty git.branch
  engine/api/migrate/default_payload.go
  engine/api/workflow.go
  engine/api/workflow/dao_hook.go
  engine/api/workflow/hook.go
  engine/api/workflow_test.go
Labels: review

#2465 feat(api): add workflow default tags after add repository webhook
  engine/api/api.go
  engine/api/migrate/default_tags.go
  engine/api/workflow.go
  engine/api/workflow/dao.go
  engine/api/workflow/dao_node.go
  engine/api/workflow_test.go
  engine/api/workflow_trigger.go
Labels: review
