Repository ovh/cds, pull requests merged in 2018-07, with the labels that each got.

#2977 docs(script): add worker cli inside script
  docs/content/workflows/pipelines/actions/builtin/script.md
Labels: doc

#2979 fix(api): send pull request reports with tests
  engine/api/workflow/workflow_run_event.go
  sdk/workflow_run.go
  sdk/workflow_run_test.go
Labels: bug

#2976 fix(api): when you update repomanager on an application, update workflow root linked
  engine/api/application.go
  engine/api/repositories_manager.go
  engine/api/workflow/dao.go
  engine/api/workflow/dao_hook.go
  engine/api/workflow/hook.go
  ui/src/app/service/application/application.store.ts
Labels: bug

#2994 fix(api): erase useinfo from url fromRepository
  engine/api/workflow/dao.go
Labels: hotfix

#2999 fix(api): be careful of nil commits list
  engine/api/workflow/dao_node_run.go
  engine/api/workflow/resync_workflow.go
Labels: hotfix

#3000 fix(ui): fix service job links for other job
  ui/src/app/views/workflow/run/node/pipeline/node.pipeline.component.ts
  ui/src/app/views/workflow/run/node/pipeline/spawninfo/spawninfo.component.ts
Labels: bug

#2984 fix(api): fix repowebhook and workflow as code
  engine/api/workflow/dao.go
  engine/api/workflow/hook.go
  ui/src/app/shared/workflow/node/hook/form/hook.form.html
Labels: bug

#2974 feat(api,worker): migrate key for gitclone, and add new key support in gitclone
  engine/api/action/action.go
  engine/api/action/builtin.go
  engine/api/api.go
  engine/api/migrate/gitclone_key_migration.go
  engine/worker/builtin.go
  engine/worker/builtin_artifact_download.go
  engine/worker/builtin_artifact_upload.go
  engine/worker/builtin_checkout_application.go
  engine/worker/builtin_deploy_application.go
  engine/worker/builtin_gitclone.go
  engine/worker/builtin_gittag.go
  engine/worker/builtin_junit.go
  engine/worker/builtin_release.go
  engine/worker/builtin_script.go
  engine/worker/cmd_upload.go
  engine/worker/main.go
  engine/worker/run.go
  engine/worker/take_workflow_node_run_job.go
  engine/worker/vcs_strategy.go
  sdk/application.go
  sdk/environment.go
  sdk/project.go
  sdk/variable.go
  sdk/vcs/keys.go
  ui/src/app/shared/action/action.component.ts
  ui/src/app/shared/action/action.html
  ui/src/app/shared/action/step/step.component.ts
  ui/src/app/shared/action/step/step.html
  ui/src/app/views/pipeline/show/workflow/pipeline.workflow.component.ts
  ui/src/app/views/pipeline/show/workflow/pipeline.workflow.html
Labels: enhancement

#3017 fix(ui): add in workflow modal the platform link to a pipeline #2991
  contrib/grpcplugins/deployment/arsenal/Makefile
  ui/src/app/shared/workflow/node/form/workflow.node.form.component.ts
  ui/src/app/shared/workflow/node/wizard/node.wizard.component.ts
  ui/src/app/shared/workflow/node/wizard/node.wizard.html
  ui/src/app/shared/workflow/trigger/workflow.trigger.component.ts
  ui/src/app/shared/workflow/trigger/workflow.trigger.html
  ui/src/assets/i18n/en.json
  ui/src/assets/i18n/fr.json
Labels: bug

#3013 Feat description icon
  engine/api/application.go
  engine/api/application/dao.go
  engine/api/navbar/navbar.go
  engine/api/pipeline.go
  engine/api/pipeline/pipeline.go
  engine/api/pipeline/pipeline_importer.go
  engine/api/project.go
  engine/api/project/dao.go
  engine/api/project/dao_dependencies.go
  engine/api/workflow.go
  engine/api/workflow/dao.go
  engine/sql/112_description_prj_pip_app.sql
  sdk/application.go
  sdk/common.go
  sdk/error.go
  sdk/exportentities/application.go
  sdk/exportentities/pipeline.go
  sdk/exportentities/pipeline_test.go
  sdk/navbar.go
  sdk/pipeline.go
  sdk/project.go
  sdk/workflow.go
  ui/src/app/model/application.model.ts
  ui/src/app/model/navbar.model.ts
  ui/src/app/model/pipeline.model.ts
  ui/src/app/model/project.model.ts
  ui/src/app/model/workflow.model.ts
  ui/src/app/service/application/application.store.ts
  ui/src/app/service/project/project.service.ts
  ui/src/app/shared/button/upload/upload.button.component.ts
  ui/src/app/views/application/add/application.add.component.ts
  ui/src/app/views/application/add/application.add.html
  ui/src/app/views/application/add/application.add.scss
  ui/src/app/views/application/show/admin/application.admin.component.ts
  ui/src/app/views/application/show/admin/application.admin.html
  ui/src/app/views/application/show/admin/application.admin.scss
  ui/src/app/views/pipeline/add/pipeline.add.component.ts
  ui/src/app/views/pipeline/add/pipeline.add.html
  ui/src/app/views/pipeline/show/admin/pipeline.admin.html
  ui/src/app/views/pipeline/show/admin/pipeline.admin.scss
  ui/src/app/views/project/add/project.add.component.ts
  ui/src/app/views/project/add/project.add.html
  ui/src/app/views/project/add/project.add.scss
  ui/src/app/views/project/list/project.list.component.html
  ui/src/app/views/project/show/admin/project.admin.component.ts
  ui/src/app/views/project/show/admin/project.admin.html
  ui/src/app/views/project/show/admin/project.admin.scss
  ui/src/app/views/project/show/application/application.list.html
  ui/src/app/views/project/show/pipeline/pipeline.list.html
  ui/src/app/views/project/show/workflow/workflow.list.html
  ui/src/app/views/workflow/add/workflow.add.component.ts
  ui/src/app/views/workflow/add/workflow.add.html
  ui/src/app/views/workflow/show/admin/workflow.admin.component.html
  ui/src/app/views/workflow/show/admin/workflow.admin.component.ts
  ui/src/app/views/workflow/show/admin/workflow.admin.scss
  ui/src/assets/i18n/en.json
  ui/src/assets/i18n/fr.json
Labels: enhancement

#3026 fix(api): fix update icon application
  engine/api/application.go
Labels: hotfix

#3027 fix(ui): fix add a trigger on a join
  ui/src/app/shared/workflow/join/trigger/trigger.join.component.ts
  ui/src/app/shared/workflow/join/trigger/workflow.trigger.join.html
Labels: bug, hotfix

#3015 fix(api,ui): add pipeline name or workflow name in a new import route for edit as code ui
  engine/api/api_routes.go
  engine/api/pipeline/pipeline_parser.go
  engine/api/pipeline_import.go
  engine/api/pipeline_import_test.go
  engine/api/workflow/dao.go
  engine/api/workflow/workflow_parser.go
  engine/api/workflow/workflow_parser_test.go
  engine/api/workflow_import.go
  engine/api/workflow_import_test.go
  sdk/error.go
  ui/src/app/service/pipeline/pipeline.service.ts
  ui/src/app/service/pipeline/pipeline.store.ts
  ui/src/app/service/workflow/workflow.service.ts
  ui/src/app/service/workflow/workflow.store.ts
  ui/src/app/views/pipeline/show/ascode-editor/pipeline.ascode.editor.component.ts
Labels: bug

#3040 fix(api): fix route for import as code via ui
  engine/api/api_routes.go
  engine/api/pipeline_import.go
  engine/api/workflow_import.go
Labels: hotfix

#3039 fix(ui): fix link to logs when you rename your workflow
  ui/src/app/shared/workflow/node/workflow.node.component.ts
  ui/src/app/views/workflow/graph/workflow.graph.component.ts
Labels: bug

#3024 feat(worker): Install and use ssh key in a step script #3022
  docs/content/workflows/pipelines/actions/builtin/script.md
  engine/api/application_key.go
  engine/api/environment/environment.go
  engine/api/environment_key.go
  engine/api/project_key.go
  engine/worker/cmd_key.go
  engine/worker/cmd_server.go
  engine/worker/main.go
  sdk/vcs/keys.go
  tests/fixtures/ITSCWRKFLW5/ITSCWRKFLW5.yml
  tests/fixtures/ITSCWRKFLW5/key-install.pip.yml
  tests/sc_workflow_key_install.yml
Labels: enhancement

#3045 feat(worker): Install and use pgp key in a step script
  docs/content/workflows/pipelines/actions/builtin/script.md
  engine/api/workflow/execute_node_job_run.go
  engine/worker/cmd_key.go
  tests/fixtures/ITSCWRKFLW5/key-install.pip.yml
  tests/sc_workflow_key_install.yml
  ui/src/app/shared/keys/list/keys.list.html
  ui/src/app/shared/keys/list/keys.list.scss
Labels: enhancement

#3046 feat(ui): add infinite scroll on sidebar run list
  engine/api/workflow_run.go
  engine/api/workflow_run_test.go
  ui/src/app/service/workflow/run/workflow.run.service.ts
  ui/src/app/views/workflow/sidebar/run/list/workflow.sidebar.run.component.ts
  ui/src/app/views/workflow/workflow.component.ts
  ui/src/app/views/workflow/workflow.html
Labels: enhancement

#3054 feat(hooks): add rabbitmq hook #547
  Gopkg.lock
  docs/content/workflows/design/hooks/_index.md
  docs/content/workflows/design/hooks/rabbitmq-hook.md
  docs/static/images/workflows.design.hooks.rabbitmq-hook.add.modal.png
  docs/static/images/workflows.design.hooks.rabbitmq-hook.add.png
  docs/static/images/workflows.design.hooks.rabbitmq-hook.platform.png
  engine/api/platform/platform_model.go
  engine/api/workflow_hook_test.go
  engine/hooks/kafka.go
  engine/hooks/rabbitmq.go
  engine/hooks/tasks.go
  sdk/exportentities/workflow.go
  sdk/hook.go
  sdk/hooks.go
  sdk/platform.go
  ui/src/app/views/workflow/sidebar/run/list/workflow.sidebar.run.component.ts
  ui/src/app/views/workflow/workflow.component.ts
  vendor/github.com/streadway/amqp/LICENSE
  vendor/github.com/streadway/amqp/allocator.go
  vendor/github.com/streadway/amqp/auth.go
  vendor/github.com/streadway/amqp/channel.go
  vendor/github.com/streadway/amqp/confirms.go
  vendor/github.com/streadway/amqp/connection.go
  vendor/github.com/streadway/amqp/consumers.go
  vendor/github.com/streadway/amqp/delivery.go
  vendor/github.com/streadway/amqp/doc.go
  vendor/github.com/streadway/amqp/fuzz.go
  vendor/github.com/streadway/amqp/read.go
  vendor/github.com/streadway/amqp/return.go
  vendor/github.com/streadway/amqp/spec091.go
  vendor/github.com/streadway/amqp/types.go
  vendor/github.com/streadway/amqp/uri.go
  vendor/github.com/streadway/amqp/write.go
Labels: enhancement

#3050 fix(api,ui): block all update of key variables
  engine/api/application_variable.go
  engine/api/environment_variable.go
  engine/api/project_variable.go
  ui/src/app/shared/variable/list/variable.html
Labels: bug

#3053 feat(hatchery): add services support in hatchery kubernetes
  engine/hatchery/kubernetes/kubernetes.go
  ui/src/app/shared/workflow/node/workflow.node.html
Labels: enhancement

#3059 fix(ui): artifacts and tests not refreshed on node run view #3049
  engine/api/workflow/execute_node_run.go
  ui/src/app/app.service.ts
  ui/src/app/model/pipeline.model.ts
Labels: bug

#3066 fix(ui): display correctly node name in title
  ui/src/app/views/workflow/sidebar/run/node/stage/job/action/action.summary.component.ts
  ui/src/app/views/workflow/sidebar/run/node/stage/job/job.summary.component.html
  ui/src/app/views/workflow/sidebar/run/node/stage/job/job.summary.component.ts
  ui/src/app/views/workflow/sidebar/run/node/stage/stage.summary.component.html
  ui/src/app/views/workflow/sidebar/run/node/stage/stage.summary.component.ts
  ui/src/app/views/workflow/sidebar/run/node/workflow.sidebar.run.node.component.html
Labels: bug

#3069 fix(worker): add error line number #3068
  engine/worker/run.go
Labels: bug

#3072 feat(hatchery): add check_registration when a new binary requirement is added
  engine/api/worker/model.go
  engine/sql/115_worker_model_check_registration.sql
  sdk/hatchery/register.go
  sdk/worker.go
  sdk/worker_easyjson.go
  ui/src/app/model/worker-model.model.ts
  ui/src/app/views/settings/worker-model/edit/worker-model.edit.html
Labels: bug

#3067 fix(worker): add retry on worker upload cmd
  engine/worker/cmd_cache.go
  engine/worker/cmd_upload.go
Labels: bug

#3077 refactor(sdk): rearrange order of elements in struct in order to minimize memory footprint
  sdk/broadcast.go
  sdk/event.go
  sdk/event_pipeline.go
  sdk/hatchery.go
  sdk/platform.go
  sdk/repositories_manager.go
  sdk/workflow.go
Labels: refactor

#3087 fix(ui): don't try to load commit if no repo is linked and fix list parameters
  ui/src/app/model/parameter.model.ts
  ui/src/app/model/workflow.model.ts
  ui/src/app/shared/parameter/list/parameter.component.ts
  ui/src/app/shared/parameter/list/parameter.html
  ui/src/app/shared/workflow/node/run/node.run.param.component.ts
  ui/src/app/shared/workflow/node/run/node.run.param.html
  ui/src/app/views/run/workflow/variables/job.variables.component.ts
  ui/src/app/views/workflow/run/node/pipeline/variables/job.variables.component.ts
Labels: hotfix

#3088 test(api): attempt to fix test timeout
  engine/api/api_test.go
Labels: bug

#3090 fix(worker): fix worker cache for weird files
  engine/worker/cmd_cache.go
  sdk/cache.go
Labels: bug

#3091 fix(hatchery): do not put worker model in error when spawn a worker for job doesn't work
  sdk/hatchery/starter.go
Labels: bug

#3095 fix: hide some field on vcs strategy
  engine/api/application.go
  engine/api/ascode.go
  engine/api/workflow/repository.go
Labels: hotfix

#3075 feat(hatchery): add service logs for hatchery kubernetes
  engine/api/workflow/process_requirements.go
  engine/hatchery/kubernetes/kill_workers.go
  engine/hatchery/kubernetes/kubernetes.go
  engine/hatchery/kubernetes/services.go
  engine/hatchery/kubernetes/types.go
  engine/hatchery/swarm/swarm_util_logs.go
  sdk/requirement.go
Labels: enhancement

#3093 feat(hatchery): add other kind of authentication for kubernetes
  engine/hatchery/kubernetes/kubernetes.go
  engine/hatchery/kubernetes/types.go
Labels: enhancement

#3102 fix(api): edit as code don't erase the workflow icon
  engine/api/workflow/workflow_importer.go
Labels: bug

#3100 fix(ui): pipeline left menu is now clickable after element is selected
  ui/src/app/views/workflow/run/node/pipeline/node.pipeline.component.ts
Labels: bug

#3107 fix(ui): fix import as code
  engine/api/pipeline/pipeline.go
  engine/api/pipeline/pipeline_importer.go
  engine/api/workflow/dao.go
  ui/src/app/service/pipeline/pipeline.service.ts
  ui/src/app/service/pipeline/pipeline.store.ts
  ui/src/app/service/workflow/workflow.service.ts
Labels: bug

#3109 fix(api): don't purge workflow run always running #3106
  engine/api/workflow/dao_run.go
  engine/api/workflow/dao_run_test.go
Labels: bug

#3118 fix(ui): fix parameters list for mode job #3116
  ui/src/app/model/workflow.model.ts
  ui/src/app/shared/parameter/list/parameter.component.ts
Labels: bug
