Repository ovh/cds, pull requests merged in 2018-10, with the labels that each got.

#3416 fix(ui): adjust font color for brightness (close #3330)
  ui/src/app/model/project.model.ts
  ui/src/app/service/helpers/helpers.service.ts
  ui/src/app/service/services.module.ts
  ui/src/app/views/project/show/project.component.ts
  ui/src/app/views/project/show/workflow/blocs/workflow.list.blocs.component.ts
  ui/src/app/views/project/show/workflow/blocs/workflow.list.blocs.html
  ui/src/app/views/project/show/workflow/labels/workflow.list.labels.component.ts
  ui/src/app/views/project/show/workflow/labels/workflow.list.labels.html
  ui/src/app/views/project/show/workflow/lines/workflow.list.lines.component.ts
  ui/src/app/views/project/show/workflow/lines/workflow.list.lines.html
Labels: bug

#3414 fix(ui): search binary in a worker model
  ui/src/app/views/settings/worker-model/list/worker-model.list.component.ts
Labels: bug

#3413 fix(api): merge pipeline parameter and default value in workflow context
  engine/api/workflow/process.go
  sdk/parameter.go
Labels: bug

#3412 docs(grpcplugins): add how to develop a grpc plugins for CDS
  contrib/grpcplugins/action/examples/nodejs/Makefile
  contrib/grpcplugins/action/examples/nodejs/README.md
  contrib/grpcplugins/action/examples/nodejs/index.js
  contrib/grpcplugins/action/examples/nodejs/package-lock.json
  contrib/grpcplugins/action/examples/nodejs/package.json
  docs/content/workflows/pipelines/actions/plugins/_index.md
  docs/content/workflows/pipelines/actions/plugins/write-plugin.md
  sdk/grpcplugin/actionplugin/nodejs/.gitignore
  sdk/grpcplugin/actionplugin/nodejs/README.md
  sdk/grpcplugin/actionplugin/nodejs/actionplugin_grpc_pb.js
  sdk/grpcplugin/actionplugin/nodejs/actionplugin_pb.js
  sdk/grpcplugin/actionplugin/nodejs/package-lock.json
  sdk/grpcplugin/actionplugin/nodejs/package.json
  sdk/grpcplugin/actionplugin/nodejs/sdk.js
Labels: doc

#3418 fix(api): update pipeline via edit as code take care of enabled (close #3366)
  engine/api/action/action.go
Labels: bug

#3419 fix(ui): display right icon for disabled worker models
  ui/src/app/views/settings/worker-model/list/worker-model.list.component.ts
  ui/src/app/views/settings/worker-model/list/worker-model.list.html
Labels: bug

#3458 fix(ui): change style of expand logs button
  ui/src/app/views/workflow/run/node/pipeline/step/step.log.component.ts
  ui/src/app/views/workflow/run/node/pipeline/step/step.log.html
  ui/src/app/views/workflow/run/node/pipeline/step/step.log.scss
Labels: bug

#3456 fix(ui): fix modal launch node with pipeline parameters when opened several times
  ui/src/app/shared/workflow/node/run/node.run.param.component.ts
  ui/src/app/shared/workflow/node/run/node.run.param.html
Labels: bug

#3464 feat(hatchery): display warning in spawn info for deprecated model (close #3422)
  sdk/hatchery/hatchery.go
  sdk/hatchery/starter.go
  sdk/messages.go
Labels: enhancement

#3497 fix(hatchery): for kubernetes replace special characters in pod name
  engine/hatchery/kubernetes/kubernetes.go
Labels: bug

#3496 chore(contrib): add vcs, hooks & hatchery in helm
  contrib/helm/cds/.gitignore
  contrib/helm/cds/README.md
  contrib/helm/cds/config.toml
  contrib/helm/cds/requirements.lock
  contrib/helm/cds/requirements.yaml
  contrib/helm/cds/templates/NOTES.txt
  contrib/helm/cds/templates/_helpers.tpl
  contrib/helm/cds/templates/api-deployment.yaml
  contrib/helm/cds/templates/api-svc.yaml
  contrib/helm/cds/templates/elasticsearch-deployment.yaml
  contrib/helm/cds/templates/elasticsearch-svc.yaml
  contrib/helm/cds/templates/hatchery-k8s-deployment.yaml
  contrib/helm/cds/templates/hatchery-k8s-svc.yaml
  contrib/helm/cds/templates/hooks-deployment.yaml
  contrib/helm/cds/templates/hooks-svc.yaml
  contrib/helm/cds/templates/ingress.yaml
  contrib/helm/cds/templates/repositories-deployment.yaml
  contrib/helm/cds/templates/repositories-pv.yaml
  contrib/helm/cds/templates/repositories-pvc.yaml
  contrib/helm/cds/templates/repositories-svc.yaml
  contrib/helm/cds/templates/secrets.yaml
  contrib/helm/cds/templates/vcs-deployment.yaml
  contrib/helm/cds/templates/vcs-svc.yaml
  contrib/helm/cds/values.yaml
Labels: feature

#3510 fix(worker): fix worker pending to the infinity after a fail on plugin start
  engine/worker/builtin.go
  go.mod
  go.sum
  sdk/grpcplugin/actionplugin/actionplugin.go
  vendor/google.golang.org/genproto/googleapis/rpc/status/status.pb.go
  vendor/google.golang.org/grpc/balancer.go
  vendor/google.golang.org/grpc/balancer/balancer.go
  vendor/google.golang.org/grpc/balancer_conn_wrappers.go
  vendor/google.golang.org/grpc/call.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/credentials/credentials.go
  vendor/google.golang.org/grpc/credentials/go16.go
  vendor/google.golang.org/grpc/credentials/go17.go
  vendor/google.golang.org/grpc/credentials/go18.go
  vendor/google.golang.org/grpc/credentials/go19.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/go.mod
  vendor/google.golang.org/grpc/go.sum
  vendor/google.golang.org/grpc/go16.go
  vendor/google.golang.org/grpc/go17.go
  vendor/google.golang.org/grpc/internal/channelz/funcs.go
  vendor/google.golang.org/grpc/internal/channelz/types.go
  vendor/google.golang.org/grpc/internal/channelz/types_linux.go
  vendor/google.golang.org/grpc/internal/channelz/types_nonlinux.go
  vendor/google.golang.org/grpc/internal/channelz/util_linux_go19.go
  vendor/google.golang.org/grpc/internal/channelz/util_nonlinux_pre_go19.go
  vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/transport/bdp_estimator.go
  vendor/google.golang.org/grpc/internal/transport/controlbuf.go
  vendor/google.golang.org/grpc/internal/transport/defaults.go
  vendor/google.golang.org/grpc/internal/transport/flowcontrol.go
  vendor/google.golang.org/grpc/internal/transport/go16.go
  vendor/google.golang.org/grpc/internal/transport/go17.go
  vendor/google.golang.org/grpc/internal/transport/handler_server.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/http_util.go
  vendor/google.golang.org/grpc/internal/transport/log.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/keepalive/keepalive.go
  vendor/google.golang.org/grpc/picker_wrapper.go
  vendor/google.golang.org/grpc/pickfirst.go
  vendor/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection.pb.go
  vendor/google.golang.org/grpc/resolver/dns/dns_resolver.go
  vendor/google.golang.org/grpc/resolver/dns/go19.go
  vendor/google.golang.org/grpc/resolver/dns/pre_go19.go
  vendor/google.golang.org/grpc/resolver/resolver.go
  vendor/google.golang.org/grpc/resolver_conn_wrapper.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/service_config.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/stickiness_linkedmap.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: bug

#3516 fix(ui): better display for RO users (close #3475)
  engine/api/permission/permission.go
  engine/api/router_permission.go
  engine/api/workflow.go
  engine/api/workflow/dao_group.go
  ui/src/app/views/project/show/application/application.list.html
  ui/src/app/views/project/show/keys/project.keys.html
  ui/src/app/views/project/show/pipeline/pipeline.list.html
  ui/src/app/views/project/show/platforms/project.platforms.html
  ui/src/app/views/project/show/workflow/workflow.list.html
  ui/src/app/views/settings/worker-model/edit/worker-model.edit.html
  ui/src/app/views/workflow/sidebar/edit/node/workflow.sidebar.edit.node.component.html
  ui/src/assets/i18n/en.json
  ui/src/assets/i18n/fr.json
Labels: bug

#3517 fix(api): better panic recovery in SSE
  engine/api/events.go
Labels: bug

#3492 feat(worker): worker check-secret command
  cli/cdsctl/workflow.go
  cli/cdsctl/workflow_log.go
  engine/worker/builtin_junit.go
  engine/worker/cmd_check_secret.go
  engine/worker/cmd_server.go
  engine/worker/logger.go
  engine/worker/main.go
  sdk/variable.go
  tests/fixtures/ITSCWCS/ITSCWCS.yml
  tests/fixtures/ITSCWCS/check-secret.pip.yml
  tests/sc_workflow_check_secret.yml
  tests/sc_workflow_key_install.yml
  tests/sc_workflow_run_cache.yml
Labels: ready-to-merge
