Repository ovh/cds, pull requests merged in 2018-08, with the labels that each got.

#3121 fix(ui): fix conditions list
  ui/src/app/shared/workflow/node/conditions/condition-form/condition.component.ts
  ui/src/app/shared/workflow/node/conditions/condition-list/condition.list.component.ts
Labels: hotfix

#3115 feat(api): stop all workflows which are running more than 24hours
  engine/api/purge/purge.go
  ui/src/app/shared/workflow/node/workflow.node.component.ts
Labels: enhancement

#3125 fix(ui): add suggest (#3124) and fix parameters list
  engine/api/suggest.go
  ui/src/app/shared/parameter/list/parameter.component.ts
  ui/src/app/shared/table/table.ts
  ui/src/app/shared/workflow/node/conditions/condition-list/condition.list.component.ts
Labels: hotfix

#3126 fix(api): do not let add run conditions with unknown operator
  engine/api/workflow/dao_node.go
  engine/api/workflow/dao_test.go
  sdk/error.go
Labels: bug

#3127 fix(ui): fix events on sidebar
  ui/src/app/service/router/router.service.ts
  ui/src/app/shared/action/action.component.ts
  ui/src/app/shared/action/action.html
  ui/src/app/shared/workflow/node/workflow.node.component.ts
  ui/src/app/views/pipeline/show/admin/pipeline.admin.html
  ui/src/app/views/pipeline/show/ascode-editor/pipeline.ascode.editor.component.ts
  ui/src/app/views/pipeline/show/ascode-editor/pipeline.ascode.editor.html
  ui/src/app/views/workflow/show/admin/workflow.admin.component.html
  ui/src/app/views/workflow/show/workflow.component.ts
  ui/src/app/views/workflow/sidebar/code/sidebar.code.component.ts
  ui/src/app/views/workflow/sidebar/code/sidebar.code.html
  ui/src/app/views/workflow/sidebar/run/node/workflow.sidebar.run.node.component.html
  ui/src/app/views/workflow/sidebar/run/node/workflow.sidebar.run.node.component.ts
  ui/src/app/views/workflow/workflow.component.ts
Labels: bug

#3128 fix(ui): advanced conditon display bug sometimes
  ui/src/app/shared/workflow/node/conditions/condition-form/condition.component.ts
  ui/src/app/shared/workflow/node/conditions/condition-form/condition.form.html
  ui/src/app/shared/workflow/node/conditions/condition-list/condition.list.component.ts
  ui/src/app/shared/workflow/node/conditions/node.conditions.component.ts
  ui/src/app/shared/workflow/node/conditions/node.conditions.html
Labels: bug

#3117 refactor(api): delete lastUpdate and add missing events
  engine/api/api.go
  engine/api/api_routes.go
  engine/api/application.go
  engine/api/application/application_delete.go
  engine/api/application/application_group.go
  engine/api/application/application_variable.go
  engine/api/application/dao.go
  engine/api/application/deprecated.go
  engine/api/application_group.go
  engine/api/application_import.go
  engine/api/application_key.go
  engine/api/application_migration.go
  engine/api/application_pipeline.go
  engine/api/ascode.go
  engine/api/environment.go
  engine/api/environment/environment.go
  engine/api/environment_group.go
  engine/api/environment_import.go
  engine/api/environment_key.go
  engine/api/environment_variable.go
  engine/api/events.go
  engine/api/group.go
  engine/api/lastupdate.go
  engine/api/pipeline.go
  engine/api/pipeline/pipeline.go
  engine/api/pipeline_group.go
  engine/api/pipeline_import.go
  engine/api/pipeline_job.go
  engine/api/pipeline_parameter.go
  engine/api/polling.go
  engine/api/project/dao.go
  engine/api/project_group.go
  engine/api/project_key.go
  engine/api/project_platform.go
  engine/api/project_variable.go
  engine/api/repositories_manager.go
  engine/api/router_util.go
  engine/api/scheduler.go
  engine/api/stage.go
  engine/api/status.go
  engine/api/trigger.go
  engine/api/worker_model.go
  engine/api/workflow.go
  engine/api/workflow/dao.go
  engine/api/workflow/execute_node_run.go
  engine/api/workflow/process.go
  engine/api/workflow_group.go
  engine/api/workflow_import.go
Labels: refactor

#3136 fix(ui): do not list platform not attached to an application
  ui/src/app/shared/workflow/node/wizard/node.wizard.component.ts
  ui/src/app/shared/workflow/node/wizard/node.wizard.html
Labels: bug

#3140 fix(api): do not return 404 if no coverage report
  engine/api/workflow/dao_node_run.go
  ui/src/app/views/workflow/run/node/workflow.run.node.component.ts
Labels: hotfix

#3141 fix(api): do not compute stop from start but from last_execution
  engine/api/purge/purge.go
Labels: bug

#3144 fix(api): fill data in last_execution
  engine/api/workflow/run_workflow.go
Labels: hotfix

#3149 fix(api): fix stop workflow run for purge
  engine/api/api.go
  engine/api/purge/purge.go
  engine/api/workflow/dao_node_run.go
  engine/api/workflow/dao_run.go
  engine/api/workflow/execute_node_run.go
  engine/api/workflow/init.go
  engine/api/workflow_run.go
Labels: bug

#3147 feat(worker): add with temp url for worker cache and fix issues
  engine/api/api_routes.go
  engine/api/cache.go
  engine/hatchery/kubernetes/kubernetes.go
  engine/worker/cmd_cache.go
  sdk/cache.go
  sdk/cdsclient/client_workflow.go
  tests/fixtures/ITSCWRKFLW4/tag-push-pull.pip.yml
  ui/resources/cds-hint.js
Labels: enhancement

#3150 fix(sdk): delete jobsTicker log
  sdk/cdsclient/client_queue.go
Labels: hotfix

#3153 fix(api): check if piptorun exist
  ui/src/app/shared/workflow/node/run/node.run.param.component.ts
Labels: hotfix

#3152 feat(ui): Display workflow run tags in web pages title
  ui/src/app/views/workflow/run/node/workflow.run.node.component.ts
  ui/src/app/views/workflow/run/workflow.run.component.ts
Labels: enhancement

#3155 doc(hosting): add info to add user without mail service
  docs/content/hosting/ready-to-run/from-binaries.md
Labels: doc

#3162 fix(sdk): add no-single-branch for git clone with depth
  sdk/vcs/git/git_clone.go
Labels: bug, hotfix

#3192 fix(api): add withIcons on routes to not fetch icon if not needed
  engine/api/application.go
  engine/api/application/dao.go
  engine/api/application/dao_dependencies.go
  engine/api/project.go
  ui/src/app/service/application/application.service.ts
Labels: bug

#3076 feat: expose git.vcs_server as a template variable
  engine/api/workflow/process_parameters.go
Labels: ready

#3202 fix(ui): artifact link from sidebar
  ui/src/app/views/workflow/sidebar/run/node/workflow.sidebar.run.node.component.html
Labels: bug

#3213 fix(ui): sidebar on node not refreshed in specific cases
  ui/src/app/shared/workflow/node/wizard/node.wizard.component.ts
  ui/src/app/shared/workflow/node/workflow.node.component.ts
  ui/src/app/views/workflow/workflow.component.ts
Labels: bug

#3200 feat(api): add git.tag support
  docs/content/workflows/pipelines/actions/builtin/checkout-application.md
  docs/content/workflows/pipelines/actions/builtin/gitclone.md
  docs/content/workflows/pipelines/variables.md
  engine/api/action/builtin.go
  engine/api/repositoriesmanager/repositories_manager.go
  engine/api/suggest.go
  engine/api/workflow/dao_node_run.go
  engine/api/workflow/execute_node_run.go
  engine/api/workflow/gorp_model.go
  engine/api/workflow/process.go
  engine/api/workflow/resync_workflow.go
  engine/api/workflow/workflow_run_event.go
  engine/hooks/tasks.go
  engine/hooks/tasks_test.go
  engine/sql/121_run_vcs_tag.sql
  engine/vcs/bitbucket/client_commit.go
  engine/vcs/github/client_commit.go
  engine/vcs/github/types.go
  engine/vcs/gitlab/client_branch.go
  engine/vcs/gitlab/client_commit.go
  engine/vcs/vcs_handlers.go
  engine/vcs/vcs_router.go
  engine/worker/builtin_checkout_application.go
  engine/worker/builtin_gitclone.go
  sdk/error.go
  sdk/event.go
  sdk/exportentities/action.go
  sdk/vcs.go
  sdk/vcs/git/git_clone.go
  sdk/workflow.go
  sdk/workflow_run.go
  tests/fixtures/ITSCWRKFLW6/ITSCWRKFLW6.yml
  tests/fixtures/ITSCWRKFLW6/clone.pip.yml
  tests/sc_workflow_git_clone_tag.yml
Labels: enhancement

#3222 fix(api): revert WorkerHeartbeatTimeout to 300s
  engine/api/worker/heartbeat.go
Labels: hotfix

#3220 fix(api,ui): some fixes
  engine/api/workflow/dao_node_run.go
  engine/api/workflow/dao_run.go
  engine/api/workflow/process.go
  engine/api/workflow/resync_workflow.go
  engine/api/workflow/workflow_run_event.go
  sdk/workflow_run.go
  ui/src/app/shared/vcs/vcs.strategy.component.ts
  ui/src/app/shared/workflow/node/run/node.run.param.component.ts
  ui/src/app/views/project/show/project.component.ts
  ui/src/app/views/workflow/run/node/summary/run.summary.component.ts
  ui/src/app/views/workflow/run/node/summary/run.summary.html
  ui/src/app/views/workflow/sidebar/edit/node/workflow.sidebar.edit.node.component.ts
  ui/src/app/views/workflow/sidebar/run/list/workflow.sidebar.run.component.html
  ui/src/app/views/workflow/sidebar/run/list/workflow.sidebar.run.component.scss
Labels: bug

#3223 fix(api): fix stop workflow run for purge, do not stop all nodes
  engine/api/workflow/dao_run.go
  engine/api/workflow/process.go
Labels: bug

#3234 feat(ui): add autocomplete for git.repository and git.tag as git.branch
  engine/api/api_routes.go
  engine/api/application.go
  engine/api/repositoriesmanager/repositories_manager.go
  engine/vcs/bitbucket/client_tags.go
  engine/vcs/bitbucket/types.go
  engine/vcs/github/client_tag.go
  engine/vcs/github/types.go
  engine/vcs/gitlab/client_branch.go
  engine/vcs/gitlab/client_tag.go
  engine/vcs/vcs_handlers.go
  engine/vcs/vcs_router.go
  sdk/repositories_manager.go
  sdk/vcs.go
  ui/resources/cds-hint.js
  ui/src/app/model/repositories.model.ts
  ui/src/app/service/application/application.workflow.service.ts
  ui/src/app/service/workflow/run/workflow.run.service.ts
  ui/src/app/shared/workflow/node/context/workflow.node.context.component.ts
  ui/src/app/shared/workflow/node/run/node.run.param.component.ts
  ui/src/app/views/workflow/sidebar/run/list/workflow.sidebar.run.component.ts
Labels: enhancement

#3243 fix(hatchery): give the ability to override default env variables
  engine/hatchery/kubernetes/kubernetes.go
  engine/hatchery/marathon/marathon.go
  engine/hatchery/swarm/swarm.go
  ui/src/app/shared/breadcrumb/breadcrumb.component.ts
  ui/src/app/shared/breadcrumb/breadcrumb.html
  ui/src/app/views/project/show/project.html
Labels: enhancement

#3247 fix(hatchery): lower case on service requirement name for kubernetes
  engine/hatchery/kubernetes/kubernetes.go
Labels: bug

#3245 fix(api): import pipeline without permission via ascode create it with right permissions
  engine/api/pipeline/pipeline_importer.go
  engine/api/pipeline_import.go
Labels: bug

#3250 fix(vcs): replace /refs/tags/ with empty string for tag list
  engine/vcs/bitbucket/client_tags.go
Labels: hotfix

#3251 fix(ui): display tags in desc order and fix autocomplete payload
  engine/vcs/github/client_tag.go
  ui/resources/cds-hint.js
Labels: bug, enhancement

#3260 fix(vcs): if no tags in github don't return error
  engine/vcs/github/client_tag.go
Labels: hotfix

#3261 fix(ui): display platforms on node correctly
  ui/src/app/shared/workflow/node/workflow.node.html
  ui/src/app/shared/workflow/node/workflow.node.scss
Labels: bug

#3259 feat(api,ui): add custom step name
  engine/api/action/children.go
  engine/api/pipeline/pipeline_action.go
  engine/api/pipeline/pipeline_stage.go
  engine/api/workflow/process.go
  engine/api/workflow/resync_workflow.go
  engine/sql/123_action_custom_name.sql
  sdk/action.go
  sdk/exportentities/action.go
  sdk/exportentities/pipeline.go
  sdk/workflow_run_easyjson.go
  tests/fixtures/action_disabled.yml
  tests/fixtures/action_git_clone.yml
  ui/src/app/model/action.model.ts
  ui/src/app/shared/action/step/step.component.ts
  ui/src/app/shared/action/step/step.html
  ui/src/app/shared/action/step/step.scss
  ui/src/app/views/workflow/run/node/pipeline/step/step.log.html
Labels: enhancement

#3278 feat(api,ui): add labels to categorize workflows
  engine/api/api_routes.go
  engine/api/project.go
  engine/api/project/dao.go
  engine/api/project/dao_dependencies.go
  engine/api/project/gorp_model.go
  engine/api/project_test.go
  engine/api/workflow.go
  engine/api/workflow/dao.go
  engine/api/workflow/dao_label.go
  engine/api/workflow_test.go
  engine/sql/125_project_label.sql
  sdk/common.go
  sdk/error.go
  sdk/project.go
  sdk/workflow.go
  ui/src/app/app.service.ts
  ui/src/app/model/project.model.ts
  ui/src/app/model/workflow.model.ts
  ui/src/app/service/project/project.resolver.ts
  ui/src/app/service/project/project.service.ts
  ui/src/app/service/project/project.store.ts
  ui/src/app/service/workflow/workflow.service.ts
  ui/src/app/service/workflow/workflow.store.ts
  ui/src/app/shared/commit/commit.list.html
  ui/src/app/shared/labels/edit/labels.edit.component.html
  ui/src/app/shared/labels/edit/labels.edit.component.scss
  ui/src/app/shared/labels/edit/labels.edit.component.ts
  ui/src/app/shared/shared.module.ts
  ui/src/app/views/project/project.module.ts
  ui/src/app/views/project/show/project.component.ts
  ui/src/app/views/project/show/workflow/blocs/workflow.list.blocs.component.ts
  ui/src/app/views/project/show/workflow/blocs/workflow.list.blocs.html
  ui/src/app/views/project/show/workflow/blocs/workflow.list.blocs.scss
  ui/src/app/views/project/show/workflow/labels/workflow.list.labels.component.ts
  ui/src/app/views/project/show/workflow/labels/workflow.list.labels.html
  ui/src/app/views/project/show/workflow/labels/workflow.list.labels.scss
  ui/src/app/views/project/show/workflow/lines/workflow.list.lines.component.ts
  ui/src/app/views/project/show/workflow/lines/workflow.list.lines.html
  ui/src/app/views/project/show/workflow/lines/workflow.list.lines.scss
  ui/src/app/views/project/show/workflow/workflow.list.component.ts
  ui/src/app/views/project/show/workflow/workflow.list.html
  ui/src/app/views/project/show/workflow/workflow.list.scss
  ui/src/assets/i18n/en.json
  ui/src/assets/i18n/fr.json
Labels: enhancement

#3279 fix(api): fix stop workflow purge
  engine/api/workflow/dao_run.go
  ui/src/app/shared/action/step/form/step.form.component.ts
  ui/src/app/shared/action/step/step.component.ts
  ui/src/app/shared/action/step/step.html
  ui/src/app/views/workflow/run/node/pipeline/step/step.log.html
  ui/src/app/views/workflow/run/node/pipeline/step/step.log.scss
Labels: bug
