Repository ovh/cds, pull requests merged in 2019-03, with the labels that each got.

#4007 (fix)Helm chart : bad indenting in persistent volumes of elasticsearch-deployment.yaml
  contrib/helm/cds/templates/elasticsearch-deployment.yaml
Labels: packaging&distribution

#4030 fix(ui): fix pipeline view with store
  engine/api/pipeline.go
  ui/src/app/store/pipelines.state.ts
  ui/src/app/views/pipeline/show/audit/pipeline.audit.component.ts
  ui/src/app/views/pipeline/show/pipeline.show.component.ts
Labels: hotfix

#4068 doc: application file format
  docs/content/docs/concepts/files/application-syntax.md
Labels: doc

#4054 fix(ui): do not export pipeline and workflows with permissions
  ui/src/app/service/pipeline/pipeline.service.ts
  ui/src/app/store/pipelines.state.ts
  ui/src/app/store/workflows.state.ts
Labels: bug, ui

#4063 fix(vcs): initialize github ratelimit values
  engine/vcs/github/http.go
Labels: bug

#4062 fix(api): check worker model requirements on job processing
  engine/api/workflow/execute_node_run.go
  engine/api/workflow/process_requirements.go
  sdk/error.go
  tests/fixtures/ITSCWRKFLW2/pipeline.yml
  tests/fixtures/ITSCWRKFLW3/build_api.pip.yml
  tests/fixtures/ITSCWRKFLW3/build_front.pip.yml
Labels: api, bug

#4064 fix(api): release book after worker model registration or error
  engine/api/worker.go
  engine/api/worker/model.go
  engine/api/worker_model.go
  engine/worker/cmd_register.go
  sdk/worker.go
Labels: api, bug

#4070 fix(cli): application variable argument order
  cli/cdsctl/application_variable.go
Labels: bug, cli

#4066 fix(cli): build cdsctl without keychain support
  cli/cdsctl/Makefile
  cli/cdsctl/configstore.go
  cli/cdsctl/configstore_darwin.go
  cli/cdsctl/configstore_linux_amd64.go
  cli/cdsctl/configstore_windows_amd64.go
  cli/cdsctl/main.go
  cli/cdsctl/update.go
  cli/cdsctl/version.go
  engine/api/download.go
  engine/update.go
  engine/worker/cmd_update.go
  sdk/cdsclient/client_download.go
  sdk/cdsclient/interface.go
  sdk/download.go
  ui/src/app/model/download.model.ts
  ui/src/app/service/download/download.service.ts
  ui/src/app/views/settings/cdsctl/cdsctl.component.ts
  ui/src/app/views/settings/cdsctl/cdsctl.html
  ui/src/app/views/settings/download/download.component.ts
  ui/src/app/views/settings/download/download.html
  ui/src/assets/i18n/en.json
  ui/src/assets/i18n/fr.json
Labels: bug, cli

#4073 feat(worker): inject environment variables without CDS_ENV prefix
  engine/worker/builtin.go
  engine/worker/builtin_script.go
  engine/worker/builtin_test.go
Labels: feature, worker

#4056 fix(contrib): use external api endpoint for vcs deployment
  contrib/helm/cds/templates/vcs-deployment.yaml
Labels: packaging&distribution

#4072 fix(api): error inserting UpdateSpawnErrorWorkerModel with UTF8 0x00
  engine/api/worker/model.go
  engine/api/worker_model.go
Labels: api, bug

#4058 fix(contrib): fix postgres dependency condition
  contrib/helm/cds/requirements.yaml
Labels: packaging&distribution

#4078 fix(api): invalid payload error is not correctly raised
  engine/api/workflow/dao.go
  engine/api/workflow/dao_hook.go
Labels: api, bug

#4060 fix(worker): shebang incorrectly interpreted in Script
  engine/worker/builtin_script.go
  engine/worker/builtin_script_test.go
Labels: bug, worker

#4061 feat(api): check downloadable binaries on startup
  engine/api/api.go
Labels: api, feature

#4067 fix(sdk): release action http timeout
  sdk/cdsclient/client_workflow.go
Labels: bug, sdk

#4065 fix(cli): command persistant flags
  cli/cdsctl/config.go
  cli/cdsctl/login.go
  cli/cdsctl/main.go
  cli/cdsctl/signup.go
  cli/cdsctl/template.go
  cli/cdsctl/template_apply.go
  cli/cdsctl/workflow_as_code.go
  cli/cdsctl/workflow_pull.go
  cli/cdsctl/workflow_push.go
  cli/cobra.go
Labels: bug, cli

#4071 fix(api): purge pipeline audits
  engine/api/api.go
  engine/api/pipeline/audit.go
Labels: api, bug

#4081 fix(vcs): avoid too big payload
  engine/hooks/webhook.go
Labels: ready-to-merge

#4089 fix(ui): do not try to select a node if workflow is not already created
  ui/src/app/views/workflow/run/workflow.run.component.ts
Labels: ready-to-merge

#4103 fix(ui): add a pipeline parameter refresh workflows store
  ui/src/app/store/pipelines.state.ts
Labels: ready-to-merge

#4107 fix(api): add git.tag in condition name
  engine/api/workflow_trigger.go
Labels: ready-to-merge

#4092 fix(api): return right permission for workflow created/updated
  engine/api/workflow.go
Labels: ready-to-merge

#4104 feat(worker): worker download from latest workflow run
  docs/content/docs/components/worker/download.md
  engine/worker/cmd_download.go
Labels: ready-to-merge

#4101 fix(worker): download in the current directory
  engine/worker/cmd_download.go
Labels: ready-to-merge

#4111 fix(api): avoid remove VCS if still used by an application
  engine/api/repositories_manager.go
  sdk/error.go
Labels: ready-to-merge

#4121 fix(cli): cdsctl version command
  cli/cdsctl/main.go
Labels: ready-to-merge

#4109 fix(worker): respect logs formats
  engine/worker/logger.go
Labels: ready-to-merge
