Repository ovh/cds, pull requests merged in 2019-05, with the labels that each got.

#4242 feat(hatchery): clean group info in model name
  sdk/hatchery/hatchery.go
Labels: feature

#4177 feat(api): delete workflow run on branch delete
  docs/content/docs/concepts/workflow/hooks/git-repo-webhook.md
  docs/content/docs/integrations/bitbucket.md
  docs/content/docs/integrations/github.md
  docs/content/docs/integrations/gitlab.md
  engine/api/api_routes.go
  engine/api/router_auth.go
  engine/api/workflow/dao_run.go
  engine/api/workflow_run.go
  engine/api/workflow_run_test.go
  engine/hooks/branch_deletion.go
  engine/hooks/tasks.go
  engine/hooks/webhook.go
  engine/sql/165_workflow_run_tag_index.sql
  sdk/cdsclient/client_workflow.go
  sdk/cdsclient/interface.go
Labels: ascode

#4264 feat(hatchery): add support of private registry
  docs/content/docs/concepts/files/worker_model-syntax.md
  docs/content/docs/tutorials/worker_model-docker/_index.md
  docs/content/docs/tutorials/worker_model-docker/docker-customized.md
  docs/layouts/partials/head.html
  docs/layouts/shortcodes/note.html
  docs/static/css/callouts.css
  engine/api/worker/gorp_model.go
  engine/api/worker/model.go
  engine/api/worker/model_import.go
  engine/api/worker_model.go
  engine/api/worker_model_test.go
  engine/hatchery/kubernetes/kubernetes.go
  engine/hatchery/kubernetes/secrets.go
  engine/hatchery/kubernetes/types.go
  engine/hatchery/swarm/swarm_util_create.go
  engine/hatchery/swarm/swarm_util_create_test.go
  engine/hatchery/swarm/swarm_util_pull.go
  sdk/error.go
  sdk/exportentities/worker_model.go
  sdk/worker.go
  sdk/worker_easyjson.go
  ui/src/app/model/worker-model.model.ts
  ui/src/app/views/settings/worker-model/form/worker-model.form.html
  ui/src/assets/i18n/en.json
  ui/src/assets/i18n/fr.json
Labels: api, feature, hatchery, ready-to-merge

#4233 fix(api): do not allow user run a workflow with cds. in payload #4230
  engine/api/workflow/dao.go
  engine/api/workflow/dao_run.go
  engine/api/workflow/process_node_test.go
  engine/api/workflow_run_test.go
  engine/api/workflow_test.go
  sdk/error.go
Labels: ready-to-merge

#4307 fix(ui): only translate string values in data table
  ui/src/app/shared/table/data-table.component.ts
  ui/src/app/shared/table/data-table.html
Labels: bug, ui

#4304 feat(engine): add download command to let users download workers binaries
  docs/content/hosting/configuration.md
  docs/content/hosting/ready-to-run/from-binaries.md
  engine/download.go
  engine/main.go
Labels: packaging&distribution

#4303 fix(hatchery/swarm): improve some logs
  engine/hatchery/swarm/swarm_util_kill.go
Labels: hatchery, refactor

#4187 chore(engine): generate cross package cover report
  engine/Makefile
  engine/api/test/test.go
  engine/api/workflow_ascode_test.go
Labels: engine, ready-to-merge, tests
