Repository ovh/cds, pull requests merged in 2019-07, with the labels that each got.

#4399 refactor(api): enable key migration
  engine/api/api.go
  engine/api/environment/environment.go
  engine/api/migrate/gitclone_key_migration.go
  engine/api/project.go
  engine/api/project/dao.go
  engine/api/project/dao_dependencies.go
  sdk/action/git-clone.go
  sdk/project.go
  sdk/variable.go
  ui/angular.json
  ui/src/app/app.service.ts
  ui/src/app/model/environment.model.ts
  ui/src/app/model/project.model.ts
  ui/src/app/service/project/project.resolver.ts
  ui/src/app/shared/action/action.event.model.ts
  ui/src/app/shared/action/step/step.event.ts
  ui/src/app/shared/project-breadcrumb/project-breadcrumb.component.ts
  ui/src/app/shared/project-breadcrumb/project-breadcrumb.html
  ui/src/app/store/project.action.ts
  ui/src/app/store/project.state.spec.ts
  ui/src/app/store/project.state.ts
  ui/src/app/views/account/account.component.ts
  ui/src/app/views/account/account.module.ts
  ui/src/app/views/account/verify/verify.component.ts
  ui/src/app/views/application/add/application.add.component.ts
  ui/src/app/views/environment/add/environment.add.component.ts
  ui/src/app/views/environment/add/environment.add.html
  ui/src/app/views/environment/add/environment.add.scss
  ui/src/app/views/environment/environment.module.ts
  ui/src/app/views/environment/environment.routing.ts
  ui/src/app/views/environment/show/advanced/environment.advanced.component.ts
  ui/src/app/views/environment/show/advanced/environment.advanced.html
  ui/src/app/views/environment/show/advanced/environment.advanced.scss
  ui/src/app/views/environment/show/environment.show.component.ts
  ui/src/app/views/environment/show/environment.show.html
  ui/src/app/views/environment/show/environment.show.scss
  ui/src/app/views/environment/show/keys/environment.keys.component.ts
  ui/src/app/views/environment/show/keys/environment.keys.html
  ui/src/app/views/environment/show/keys/environment.keys.scss
  ui/src/app/views/project/project.module.ts
  ui/src/app/views/project/project.routing.ts
  ui/src/app/views/project/show/environment/environment.list.component.ts
  ui/src/app/views/project/show/environment/environment.list.html
  ui/src/app/views/project/show/environment/environment.list.scss
  ui/src/app/views/project/show/environment/form/environment.form.component.ts
  ui/src/app/views/project/show/environment/form/environment.form.html
  ui/src/app/views/project/show/environment/form/environment.form.scss
  ui/src/app/views/project/show/environment/form/environment.form.spec.ts
  ui/src/app/views/project/show/environment/list/environment.list.component.ts
  ui/src/app/views/project/show/environment/list/environment.list.html
  ui/src/app/views/project/show/environment/list/environment.list.scss
  ui/src/app/views/project/show/environment/list/environment.list.spec.ts
  ui/src/app/views/project/show/environment/list/item/environment.component.ts
  ui/src/app/views/project/show/environment/list/item/environment.html
  ui/src/app/views/project/show/environment/list/item/environment.scss
  ui/src/app/views/project/show/environment/list/item/environment.spec.ts
  ui/src/app/views/project/show/project.component.ts
  ui/src/app/views/project/show/project.html
  ui/src/assets/i18n/en.json
  ui/src/assets/i18n/fr.json
Labels: engine, refactor, ui

#4454 fix(ui): update hook button
  sdk/grpcplugin/actionplugin/nodejs/package.json
  ui/src/app/shared/workflow/wizard/hook/hook.form.html
Labels: hotfix, integration

#4455 fix(ui): load environment names
  ui/src/app/service/project/project.resolver.ts
Labels: bug, ui

#4472 fix: clover coverage
  engine/worker/builtin_coverage.go
Labels: hotfix

#4490 fix(ui): display logs
  ui/src/app/views/workflow/run/node/pipeline/step/step.log.component.ts
Labels: hotfix
