Repository ovh/cds, pull requests merged in 2019-06, with the labels that each got.

#4299 refactor(api): loaders and permission middleware for workflow template
  cli/cdsctl/template.go
  cli/cdsctl/template_apply.go
  engine/api/action.go
  engine/api/action/loader.go
  engine/api/api_routes.go
  engine/api/permission.go
  engine/api/project.go
  engine/api/templates.go
  engine/api/templates_test.go
  engine/api/workflow.go
  engine/api/workflow/workflow_exporter.go
  engine/api/workflow/workflow_importer.go
  engine/api/workflowtemplate/aggregate.go
  engine/api/workflowtemplate/aggregate_test.go
  engine/api/workflowtemplate/dao.go
  engine/api/workflowtemplate/dao_test.go
  engine/api/workflowtemplate/import.go
  engine/api/workflowtemplate/loader.go
  engine/api/workflowtemplate/loader_test.go
  sdk/cdsclient/client_template.go
  sdk/cdsclient/interface.go
Labels: api, refactor

#4335 feat(contrib): add badge uservice
  contrib/uservices/badge/.gitignore
  contrib/uservices/badge/Cargo.toml
  contrib/uservices/badge/README.md
  contrib/uservices/badge/diesel.toml
  contrib/uservices/badge/migrations/.gitkeep
  contrib/uservices/badge/migrations/00000000000000_diesel_initial_setup/down.sql
  contrib/uservices/badge/migrations/00000000000000_diesel_initial_setup/up.sql
  contrib/uservices/badge/migrations/2019-04-09-192144_create_runs/down.sql
  contrib/uservices/badge/migrations/2019-04-09-192144_create_runs/up.sql
  contrib/uservices/badge/src/badge/handlers.rs
  contrib/uservices/badge/src/badge/mod.rs
  contrib/uservices/badge/src/configuration.rs
  contrib/uservices/badge/src/database.rs
  contrib/uservices/badge/src/error.rs
  contrib/uservices/badge/src/kafka.rs
  contrib/uservices/badge/src/main.rs
  contrib/uservices/badge/src/middlewares/auth.rs
  contrib/uservices/badge/src/middlewares/mod.rs
  contrib/uservices/badge/src/models.rs
  contrib/uservices/badge/src/run/handlers.rs
  contrib/uservices/badge/src/run/mod.rs
  contrib/uservices/badge/src/schema.rs
  contrib/uservices/badge/src/service.rs
  contrib/uservices/badge/src/web.rs
Labels: feature

#4381 fix(ui): create empty array when add first stage conditions
  ui/src/app/shared/conditions/conditions.component.ts
Labels: bug, ui
