Repository ovh/cds, pull requests merged in 2020-06, with the labels that each got.

#5231 feat(api): remove default region
  engine/api/api.go
  engine/api/workflow/gorp_model.go
  engine/api/workflow/init.go
  engine/api/workflow_queue_test.go
Labels: ready-to-merge

#5233 feat(hatcheries): ignoreJobWithNoRegion conf
  engine/service/types.go
  sdk/hatchery/hatchery.go
  sdk/hatchery/types.go
Labels: ready-to-merge

#5230 fix(hook): store md5 before sending event to channel
  engine/hooks/gerrit.go
Labels: ready-to-merge

#5235 refactor(api): variables dao
  engine/api/application/application_exporter.go
  engine/api/application/application_parser.go
  engine/api/application/dao_variable.go
  engine/api/application/dao_variable_test.go
  engine/api/application/gorp_model.go
  engine/api/application_export_test.go
  engine/api/application_import_test.go
  engine/api/application_variable.go
  engine/api/application_variable_test.go
  engine/api/environment.go
  engine/api/environment/dao_variable.go
  engine/api/environment/dao_variable_test.go
  engine/api/environment/environment_exporter.go
  engine/api/environment/environment_importer.go
  engine/api/environment/environment_importer_test.go
  engine/api/environment/environment_parser.go
  engine/api/environment/gorp_model.go
  engine/api/environment_export_test.go
  engine/api/environment_import_test.go
  engine/api/environment_test.go
  engine/api/environment_variable.go
  engine/api/environment_variable_test.go
  engine/api/event/publish_application.go
  engine/api/event/publish_environment.go
  engine/api/event/publish_project.go
  engine/api/project/dao_variable.go
  engine/api/project/dao_variable_test.go
  engine/api/project/gorp_model.go
  engine/api/project_test.go
  engine/api/project_variable.go
  engine/api/project_variable_test.go
  engine/api/workflow/execute_node_job_run.go
  engine/api/workflow/run_workflow_test.go
  engine/api/workflow_import_test.go
  sdk/application.go
  sdk/environment.go
  sdk/event_application.go
  sdk/event_environment.go
  sdk/event_project.go
  sdk/exportentities/environment.go
  sdk/parameter.go
  sdk/project.go
  sdk/variable.go
Labels: waiting

#5244 fix(api,sdk): allow to retry request when conflict due to database lock
  engine/api/application_import_test.go
  engine/api/database/gorpmapping/dao.go
  engine/api/environment.go
  engine/api/environment/environment_parser.go
  engine/api/environment_import_test.go
  engine/api/integration.go
  engine/api/pipeline.go
  engine/api/project.go
  engine/api/workflow/dao_label.go
  engine/api/workflow/workflow_importer.go
  sdk/cdsclient/http.go
  sdk/error.go
Labels: ready-to-merge

#5248 fix(api,ui): return empty app stats and timeline if no elastic service
  engine/api/timeline.go
  engine/api/ui.go
  sdk/overview.go
  ui/src/app/views/application/show/home/application.home.component.ts
  ui/src/app/views/application/show/home/application.home.html
Labels: ready-to-merge

#5252 fix(ui): nodes not displayed and exception to get dimensions
  ui/src/app/views/workflow/graph/workflow.graph.component.ts
  ui/src/app/views/workflow/sidebar/code/sidebar.code.component.ts
Labels: ready-to-merge

#5255 fix(api): load application no-ascode
  engine/api/application.go
Labels: hotfix

#5241 refactor(api): remove network requirement
  docs/content/docs/concepts/requirement/_index.md
  docs/content/docs/concepts/requirement/requirement_network.md
  engine/api/workflow/process_requirements.go
  engine/hatchery/local/local.go
  engine/sql/207_remove_network_requirement.sql
  engine/worker/internal/action/builtin_script.go
  engine/worker/internal/requirement.go
  engine/worker/internal/requirement_test.go
  engine/worker/internal/take.go
  sdk/cdsclient/http_websocket.go
  sdk/exportentities/pipeline.go
  sdk/hatchery/hatchery.go
  sdk/requirement.go
  sdk/requirement_test.go
  tests/03_clictl_admin_plugin_and_integrations.yml
  tests/04_sc_workflow_integration_deploy_plugin_req.yml
  tests/06_sc_workflow_with_marathon.yml
  tests/fixtures/ITSCWRKFLW17/pipeline.yml
  tests/fixtures/plugins/hello-it-plugin-binary.yml
  tests/test.sh
  ui/src/app/shared/requirements/form/requirements.form.component.ts
  ui/src/app/shared/requirements/form/requirements.form.spec.ts
  ui/src/app/shared/requirements/list/requirements.list.component.spec.ts
  ui/src/assets/i18n/en.json
  ui/src/assets/i18n/fr.json
Labels: ready-to-merge

#5249 feat(api,ui): enable websocket for all
  engine/api/api.go
  engine/api/api_routes.go
  engine/api/events.go
  engine/api/router.go
  engine/api/router_metrics.go
  sdk/cdsclient/http_sse.go
  ui/src/app/app.component.ts
  ui/src/app/event.service.ts
  ui/src/assets/worker/common.js
  ui/src/assets/worker/eventsource.js
  ui/src/assets/worker/sharedWorker.js
  ui/src/assets/worker/webWorker.js
Labels: ready-to-merge

#5254 fix(hatchery): count CPUs using flavor list instead of data from server
  engine/hatchery/openstack/spawn.go
  engine/hatchery/openstack/spawn_test.go
  engine/vcs/gerrit/client_pull_request.go
Labels: ready-to-merge

#5258 fix(ui): load project deps+ fix loading application and pipeline after creation
  sdk/project.go
  ui/src/app/store/applications.state.ts
  ui/src/app/store/pipelines.state.ts
  ui/src/app/store/project.action.ts
  ui/src/app/store/project.state.ts
  ui/src/app/views/home/filter/home.filter.component.ts
  ui/src/app/views/project/show/application/application.list.component.ts
  ui/src/app/views/project/show/application/application.list.html
  ui/src/app/views/project/show/environment/environment.list.component.ts
  ui/src/app/views/project/show/environment/environment.list.html
  ui/src/app/views/project/show/pipeline/pipeline.list.component.ts
  ui/src/app/views/project/show/pipeline/pipeline.list.html
  ui/src/app/views/project/show/project.component.ts
  ui/src/app/views/project/show/workflow/workflow.list.component.ts
  ui/src/app/views/project/show/workflow/workflow.list.html
Labels: ready-to-merge

#5265 fix(worker, cdn): logs
  engine/api/workflow/execute_node_job_run.go
  engine/api/workflow_queue.go
  engine/api/workflow_run.go
  engine/cdn/cdn.go
  engine/cdn/cdn_log.go
  engine/cdn/cdn_log_test.go
  engine/hatchery/serve.go
  engine/worker/internal/run.go
  engine/worker/internal/take.go
  engine/worker/internal/types.go
  sdk/log/hook/hook.go
  sdk/log/hook/stack.go
  sdk/log/hook/throttle.go
  sdk/log/log.go
Labels: ready-to-merge
