Repository ovh/cds, pull requests merged in 2020-02, with the labels that each got.

#4936 fix(ui): edit custom action with key parameter display input correctly
  ui/src/app/shared/parameter/value/parameter.value.html
Labels: bug, ui

#4931 fix(api): return right error on add workflow group
  engine/api/group/workflow_group.go
  engine/api/workflow_group.go
Labels: api, bug

#4951 fix(ui): check if application exist on workflow component
  ui/src/app/views/workflow/workflow.html
Labels: hotfix

#4930 fix(api,ui): audit on pipeline with template is now correct
  engine/api/pipeline/audit.go
  engine/api/pipeline/pipeline_parser.go
  ui/src/app/shared/diff/diff.ts
  ui/src/app/shared/workflow-template/apply-form/workflow-template.apply-form.html
  ui/src/app/views/pipeline/show/audit/pipeline.audit.component.ts
Labels: api, ascode, bug

#5006 ovh/cds#5005 Fix gitlab user auth with custom endpoint
  engine/api/authentication/gitlab/gitlab.go
Labels: ready-to-merge
